<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>HavenOS.Spaces</AssemblyName>
    <RootNamespace>HavenOS.Apps.Spaces</RootNamespace>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Tests\**\*.cs" />
    <ProjectReference Include="..\shared\src\Haven.Application\Haven.Application.csproj" />
    <ProjectReference Include="..\shared\src\Haven.Core\Haven.Core.csproj" />
  </ItemGroup>
</Project>
