"""Source-preserving B3 browser requirement/procedure ledger; never marks runtime PASS."""
from pathlib import Path
import json,csv,re,hashlib,collections
base=Path('/workspace/team-b-evidence/sol-happy-20261003')
out=base/'b3'
paragraphs=json.loads((base/'source/paragraphs.json').read_text())
manifest=json.loads((base/'source/manifest.json').read_text())
apps=[('Mail',270648,290972,'9to1.Mail','9to1 Workspace/Mail'),('Games',290972,320600,'9to1.Games',None),('Planner',555689,580796,'9to1.Planner','9to1 Workspace/shared/src/Haven.Core/Planner'),('Picture',603735,631740,'9to1.Picture','9to1 Workspace/Picture'),('Wave',631740,658708,'9to1.Wave','9to1 Workspace/Wave'),('Motion',658708,688662,'9to1.Motion','9to1 Workspace/Motion'),('Dev',771113,812451,'9to1.Dev','9to1 Workspace/Dev'),('Stacks',812451,862474,'9to1.Stack','9to1 Workspace/Stacks'),('Terminal',911016,942216,'9to1.Terminal','9to1 Workspace/Terminal'),('Mini Computer',942216,979968,'9to1.MiniComputer','9to1 Workspace/MiniComputer'),('Browse',979978,1000553,'9to1.Browse','9to1 Workspace/Browse'),('Maps',1000553,1020186,'9to1.Maps','9to1 Workspace/shared/src/Haven.Core/Maps'),('Launcher',1020186,1026640,'9to1.Launcher',None),('Shelf',1026640,1032293,'9to1.Shelf','9to1 Workspace/shared/src/Haven.Core/Shelf')]
common=[('General Rules',1,57534),('Common apps/Web',102889,114171),('Authentication',114195,115430),('Terra-form shared',1238694,1253145),('Variants',1299027,1303935),('Terra-form cross-app',1303935,1315675),('Sol Happy',1315675,1342106)]
procedures={
'COMMON-CONTINUITY':('All browser editor/storage controls; exact artifact deep link; Files rename/move/history/share', 'Sign in in two clean browser profiles and native client using authorised test identities. Create populated artifact A; record canonical IDs and committed revision from authenticated owner API. Edit/save in browser, open native, edit/save, reopen browser. Rename/move while open; inspect revision history; share with reader then revoke. Make concurrent incompatible edits from two clients using identical base revision, interrupt save, reconnect/retry with same operation ID. Compare actual structure/content/revisions and affected source objects; do not accept success labels.'),
'COMMON-AI':('Persistent floating AI bar; visible Read-only/Write switch; shared compose invocation', 'Select a real object with off-screen siblings. Request semantic analysis in Read-only and record permitted context IDs. Request a mutation and verify unchanged authoritative revision; switch Write and perform authorised owning-app action. Repeat with read-only host/reader ACL, denied/expired trust and unavailable AI. Verify no mutation or private cloud upload in denied cases, one revision/audit on authorised action, manual editing remains usable, cross-app invocation retains target owner ID.'),
'COMMON-A11Y':('Owning editor panes, menus, dialogs and populated special controls', 'At equivalent desktop viewport and narrow/touch sizes, use keyboard alone through every named control. Inspect screen-reader names, roles, selection, values and item structure. Exercise 200% zoom/scaling, themes/high contrast, reduced motion; inspect focus/return focus, hover/selected/disabled/loading/empty/error/read-only/conflict/missing-source states. Record real screenshots/traces and interactions. Ensure AI bar does not cover Save/Close/Back and pointer-only actions have usable equivalents.'),
'COMMON-PERFORMANCE':('Populated editor, long lists/graphs/timelines, close/reopen/navigation', 'Use progressively larger representative production-format fixtures with recorded sizes/seed. Measure startup, editing, scrolling, playback where relevant, memory, request counts and retained subscriptions on repeat open/close/navigation. Run background work concurrently; cancel it. Check bounded streaming/virtualisation/cache cleanup and no silent content truncation. Record measurements against canonical thresholds; unresolved runtime/capacity targets remain BLOCKED, never invented.'),
'COMMON-FAILURE':('Error, reconnect, retry, job progress/cancellation and recovery surfaces', 'In isolated non-production test data, exercise each named error with invalid/missing IDs, incompatible schema, denied permissions, unavailable provider, cancellation, disconnection and stale expected revision. Interrupt one mutation before authoritative commit and retry same operation identity. Inspect structured code, scope, recoverability, precise partial outcomes and job revision/result. Reopen second client; verify prior valid state/draft/source survived and consequential effects were not duplicated.'),
'COMMON-DONOR':('Entire applicable mature donor menu/command/shortcut/settings surface', 'Pin real selected donor source/revision/licence and inspect its applicable operation inventory including QoL, import/export, security, recovery, keyboard and performance. For each donor operation, record Preserve/9to1 replacement/exact canonical exception and corresponding real browser journey and expected content effect. Independently compare donor behaviour with canonical replacement. Source inclusion and build graph do not prove parity; no unidentified donor operation can disappear from coverage.'),
'COMMON-API':('Corresponding owning-app command/menu/shortcut and typed API action', 'Provision authorised populated canonical fixture; invoke the exact canonical API entry in this row with stable IDs and declared typed arguments; repeat equivalent user operation through actual UI. Compare content, revision, owner permission/risk, result/error, idempotency and audit events. Enumerations exercise pagination; subscriptions resume from cursor; jobs cancel and reconnect. No actual browser control or endpoint has been verified; record missing wiring before execution rather than inventing routes.'),
'COMMON-IDENTITY':('Owning object details, rename/reorder/open/save and cross-app references', 'Create two objects with duplicate display names where allowed. Record stable IDs and schema/revision before rename, reorder and Files move. Open via source owner and secondary reference; inspect both canonical results. Save/reopen/export/import with supported native format, unknown/newer schema and denied source role. Verify typed identities, lifecycle, ownership, no unmanaged copy or guessed schema and conflicts preserve both changes.'),
'COMMON-SECURITY':('Sign-in, account context, trust prompt, source/content privacy and audit', 'Use owner, reader and unrelated-account clean sessions. Attempt named read/mutation before grant, after revoke/expiry, and after account/organisation switch. Verify backend rejection and absence of private cache/AI/network leaks. Inspect approval impact/risk/caller identity, structured denied outcome and audit. Execute only isolated harmless effects; no actual sends, charges, public publishing or production faults without explicit approved test scope.'),
'MAIL':('Three panes/navigation, message reader, compose, Outbox, scheduled send, rules/settings', 'Connect isolated Gmail, Microsoft and generic IMAP/SMTP accounts through real authenticated services. Populate distinct messages with matching subjects/Internet Message-ID, labels versus folders, safe/hostile HTML, attachments and aliases. Exercise each row’s reading/compose/provider operation using exact AccountID-scoped IDs. Offline-cache/read and queue edits/send, restart and reconnect; test draft conflict, provider revoke and send refusal. Verify provider state and second-client content, Outbox lifecycle, Undo hold before irreversible submission, truthful scheduling executor and no tracking/script leakage. Test attachments through canonical Files; do not send outside explicitly authorised test recipients.'),
'GAMES':('Development and Creation/Rendering workspaces, scene/components, inspector, graphs, modeller, run/debug/export', 'Create a real maintained Godot/Blender-derived canonical project with 2-player shared/individual state, C# plus C++ exposed component, controller/WASD movement, starter Player/vehicles/water/lava and a CUI HUD. Exercise row’s creation/control/renderer operation, direct manual authoring and typed API; persist/reopen scene/script/graph/component IDs. Run/inspect actual gameplay and standalone modelling/rendering; rebind per-player keys, hot swap devices, test component dependency/version migration, graph type rejection, real debugging/profiling/export and unsupported hardware fallback. Inspect actual native structure/results, not labelled prefab controls or opaque AI bitmap.'),
'PLANNER':('Today/Day/Week/Month/Agenda/Tasks grids, Schedule/Countdown/Assignments, recurrence/provider/details', 'Create timezone-aware and all-day events spanning DST, a due-only task, weighted nested required/optional assignment, schedule with current timed item, linked countdown and a recurring series. Exercise row operation by keyboard/direct controls and typed API. Schedule/unschedule same task, move linked event, snooze reminder, edit occurrence/this-and-following/whole series. Observe live schedule percentages, next countdown and notification occurrence identity. Import/export .ics; connect real provider calendar, edit concurrently/offline. Attach canonical Maps/Mail/Files references and test authorised overdue Automation→Mail with denied control. Verify original times, IDs, required-item completion and no duplicate Events.'),
'PICTURE':('Create/Edit/Generate/Browse, canvas/object/selection tools, Manual Layers, adjustments, export and Variants', 'Create Raster, Vector and Hybrid documents with shared editable text/ink, paths/Bézier handles, raster subject, mask, linked asset and artboard. Exercise each stated tool/operation and inspect actual ElementGraph/LayerGraph and revision. Switch automatic/manual modes, circle/extract/move subject with scoped background repair, generate/sketch/region-edit through real configured model, retain source/provenance. Save/reopen; export raster/vector/animated samples with profile/metadata options; verify full quality and explicit flattening. Run layer/mask/transform/adjustment Variants comparisons including conflicting raster changes, stale merge and interrupted save. Confirm ink/text/shared engines and canonical FileID continuity.'),
'WAVE':('Multitrack timeline/transport, mixer/effects, spectral, sequencer/piano roll, SFX graph, TTS/transcript/censorship/stems', 'Create a multitrack project with a recorded take, imported mixed audio, sequence notes/patterns/instrument, native SFX graph and SpeechSynthesis text/voice/prosody. Exercise each row operation on stable TrackID/ClipID/component IDs with real audio output. Test split/trim/ripple/fades/mix/routing/effects/automation, time-frequency repairs, enhancement/denoise preview and noise profile. Generate music/SFX/TTS through real configured provider then manually edit their structured native sources. Review exact phrase and semantic-theme censorship ranges; apply/undo treatment; Split Stems creates derived tracks preserving original. Interrupt recording and recover chunks. Export requested scopes/codecs and verify timing/sample quality plus Motion/Present same canonical references.'),
'MOTION':('Media/Viewer/Inspector/Timeline, node editor, captions/curves/proxies, render queue', 'Create populated multi-track sequence with video, still Picture asset, editable title, linked audio, mask/keyframes and nested sequence. Execute row’s frame-exact NLE/property/graph operation; compare structured canonical source ranges and revisions, then undo/reopen. Branch a MotionCompositionGraph, use custom transition progress and procedural/keyframe/tracking contribution; reject incompatible ports; correct mask manually. Generate captions/transcript ripple edits, proxies and typed AI highlights/reframe/subtitles. Edit audio in Wave and return same reference. Export original quality/captions; interrupt/cancel revision-pinned render, edit source during job and verify pinned result and explicit partial failure; relink offline media without new ElementID.'),
'DEV':('New Project/editor, Problems/Test Explorer/debugger, dependencies/toolchains, AI review, CUI Builder/preview/environment selector', 'Open real C#/.NET, C/C++ and Python multi-root projects with known diagnostics/tests, unrelated pre-existing user edits and native manifests/lockfiles. Select explicit authorised remote environment for browser execution; read/edit/save canonical source. Exercise row operation with real LSP, build stage, DAP, package manager, test identity or CUI source model; validate resulting files/logs/provider state. Denied/untrusted workspace must not execute. AI multi-file edit records only its distinct change set; review hunks and revert amid overlapping user edits. Preview bidirectional CUI while preserving unsupported code and last-valid render on failure. Test multi-target extension isolated host and Sites/AI Studio/Stack exact-ID handoffs. VM actions remain unavailable under Mini Computer exemption until approved provider exists.'),
'STACKS':('Home/project tabs, lineage/domain tree, changes/history/diff/conflicts/Change Requests, Root/Subroot/Freeze, release/audit', 'Provision isolated Files-backed and dedicated GitHub-backed project with Main→Branch→Twig→Leaf. Record IDs/base/effective revisions; edit two domains concurrently, cascade safe ancestor change and conflict one resource. Verify owned +A/-D excludes inherited delta, tombstones/renames preserve lineage. Promote pinned CR with checks/approvals, then mutate source to invalidate stale approval. Test reviewed AI/manual conflict choices, Root lock/nonoverlapping Subroot, scoped Freeze expiry. Inspect protected companion ref and deterministic restore after isolated damage. Attempt private-ancestry projection and guard-protected raw Git; verify backend refusal. Sweep preview/consolidation, prune/restore same DomainID, blocked purge, opt-in autocommit and remote-failure states. Cross-client source/ACL/history inspect real provider result.'),
'TERMINAL':('Real PTY tabs/panes, AI/Command switch, $Ask, verification, environment/profiles/jobs/history', 'Connect approved isolated remote/server PTY provider with explicit EnvironmentID and host-key identity. Run interactive REPL/full-screen ANSI program, resize, stdin/signals and sustained output. Ordinary commands bypass LLM. $Ask scoped error explanation must cause zero process/file/API mutation; suggestions are not executed. AI resolved low-risk request and denied dangerous request show exact target/impact and protected typed action. Switch modes preserving session/cwd; reopen panes without replaying commands. Create persistent harmless scheduled action in actual scheduler, close tab then inspect/cancel same ID. Test SSH mismatch, disconnect/reconnect proof, multiline paste exactness, secret exclusion, truncation, Stack guards and canonical Dev/Data/Files integration. Without provider execution remains BLOCKED.'),
'BROWSE':('Tab/profile/workspace/groups/split/orientation, internal routes/newtab Search/AI, permissions/extensions/Site Enhancer', 'Use actually supported execution environment; create Firefox-default and Chromium tabs with separate engine-private storage and mixed ProfileIDs in one workspace/split. Persist per-site engine rule, switch engine without changing TabID; test all four tab orientations/group operations and renderer recovery. Open registered native 9to1:// surface and distinct cui://, browse:// and https:// namespaces; confirm real canonical owner APIs and unprivileged origin denial. Customize New Tab, Search default/dual-provider two real tabs, canonical Dulche mentions, scoped browsing and denied consequential action. Install authorized test extension/Enhancer and inspect permissions/engine capability state. Validate upstream update/promote/rollback with pinned builds. Browser-hosted web engine/profile interception is an unresolved capability, never imitated by iframe.'),
'MAPS':('Map/search-AI/location picker/place detail, routes/journeys/POI layers/offline regions', 'Connect real approved map/search/routing/offline/transit providers. Search ambiguous address and near-me with precise permission denied; verify provenance/confidence and no fabricated position. Drop private coordinate landmark, route to off-graph final point, explicitly submit community POI after duplicate check and then verify/correct/report. Create saved journey with travel/bench stop/wait/activity/manual shortcut and required intent; reroute disruption without deleting required steps. Share with private dependencies denied; download licensed region and test offline search/routing plus freshness/storage limits. Attach RouteID to Planner and change route while viewed. Test shared embeds and exact disclaimer; no public unlimited OSM/Nominatim dependency or implicit OSM publication.'),
'LAUNCHER':('Canonical home pages/drawer/dock/folders/widgets/customisation configuration; actual OS host integration', 'Respect Android/9to1-OS home-launcher purpose; no browser can claim to replace OS home assignment. Through an authorised same-model configuration/service capability if approved, create pages/drawer/dock/folders and configure grid/icon/gestures/widgets, save/reopen and apply on real enrolled native host. Verify InstalledApplicationIDs survive update and work-profile separation; denied widget/package capability remains unavailable. Donor Lawnchair parity requires actual native-host behaviour. Global web inclusion versus native-only boundary needs coordinator clarification; no invented exemption.'),
'SHELF':('LaunchItem library/search-AI, manual/smart collections, context actions, unavailable-target state', 'Register real authorised app/project/FileID/URL/game targets from owning providers. Put same LaunchItem in two collections, reorder/tag/favourite and use reliable typed smart predicate; verify no duplicate target. Discover permission-scoped inventory/manual import and deny unrelated enumeration. Sync to second client lacking target and preserve unavailable entry. Open through actual owner/provider (browser URL or canonical app deep link; enrolled device only if approved), inspect real action result and target identity. AI collection examples use real discovered items and risk controls.'),
'VARIANTS':('Picture document/version Variants panel, branch status/deep links, compare/navigation/selected merge/conflict recovery', 'In Picture create variant from base RevisionID with stable VariantID; edit layer/mask/transform/adjustment and incompatible raster content. Switch with unsaved changes, rename/duplicate, reopen deep link at chosen branch. Compare explicit base/source/target; navigate additions/removals/conflicts with textual status and preview selected change effects. Independently edit source/target to invalidate preview; reject stale/idempotent retry. Resolve Keep target/Use source/manual or faithful whole-version choice into new target revision preserving both histories. Cancel/interrupt merge and archive/recover without deleting only content. Picture structural assertions are mandatory; other six apps handed to owning B2/B4, never counted B3 verified.'),
'TERRA-FORM':('Owning specialist embedded source/editor, shared context/selection/reference/permission, Picture Variants', 'Reference populated Picture/Wave/Motion/Maps/Planner/Dev/Stack source from authorised Files organisation/Link/Boards/Paths/Replay surface. Inspect exact canonical source/section/revision policy; edit through source-owner API with same selection, save state and current permissions. Move/rename/delete selected source section, revoke source while host remains shared, close popup and return focus/viewport. Remove placement versus original deletion; native export dependency manifest and explicit portable disclosure; second client validates no duplicated or leaked sources. Historical Replay checkpoint stays at pinned revision after source changes. Unsupported combinations state precise limitation; no flattening substitution.'),
'OPERATING-CONTRACT':('Coordinator/reviewer evidence and actual runtime/release procedures', 'Review exact clause against repository authority, owned diffs, source/test integrity, real donor/runtime evidence, safe external scope and independent reviewer. Record a reproducible artifact or blocker, not self-attestation. Recheck canonical revision and rerun affected acceptance on final integrated frontend/backend candidate; no unit/build result substitutes for runtime, subjective/objective or Definition of Done gates.'),
}
head=[]; rows=[]; excluded=[]
for p in paragraphs:
 text=p['text'].strip(); ix=p['index']
 level=p['heading']
 if level!='NORMAL_TEXT':
  if text:
   if level=='TITLE':head=[text]
   else:
    n=int(level.split('_')[-1]); head=head[:n]; head.append(text)
  continue
 app=next((a for a in apps if a[1]<=ix<a[2]),None)
 group=next((c for c in common if c[1]<=ix<c[2]),None)
 if not text or not (app or group): continue
 owner=app[0] if app else group[0]
 # Include every substantive prose/list/example as inherited product scope. Optional-only stays visible.
 norm=re.findall(r'\b(MUST NOT|SHOULD NOT|SHALL NOT|MUST|SHOULD|SHALL|REQUIRED|RECOMMENDED|OPTIONAL|MAY)\b',text,re.I)
 strength='MANDATORY' if any(x.upper().startswith(('MUST','SHALL','REQUIRED')) for x in norm) else 'DEFAULT-REQUIRED SHOULD' if any(x.upper().startswith(('SHOULD','RECOMMENDED')) for x in norm) else 'OPTIONAL/CONDITIONAL (retained)' if norm else 'PRODUCT/INHERITED REQUIREMENT (review applicability)'
 h=' / '.join(head); low=(h+' '+text).lower()
 category=app[0].upper().replace(' ','') if app else 'OPERATING-CONTRACT'
 if category=='MINICOMPUTER':category='COMMON-IDENTITY'
 if group: category='VARIANTS' if owner=='Variants' else 'TERRA-FORM' if owner.startswith('Terra-form') else 'OPERATING-CONTRACT'
 if 'api' in h.lower() or text.startswith('9to1.'):category='COMMON-API'
 elif any(s in h.lower() for s in ['donor','upstream']):category='COMMON-DONOR'
 elif any(s in h.lower() for s in ['accessibility','responsive layout']):category='COMMON-A11Y'
 elif any(s in h.lower() for s in ['performance','resource behaviour','realtime safety']):category='COMMON-PERFORMANCE'
 elif any(s in h.lower() for s in ['failure','recovery','resilience']):category='COMMON-FAILURE'
 elif any(s in h.lower() for s in ['permission','security','privacy','risk','authentication']):category='COMMON-SECURITY'
 elif any(s in h.lower() for s in ['ai bar','ai action boundary','dulche context','persistent contextual','cross-app invocation']):category='COMMON-AI'
 elif any(s in h.lower() for s in ['canonical','identity','data invariants']):category='COMMON-IDENTITY'
 elif any(s in h.lower() for s in ['interoperability','files and','cross-device','sync, history']):category='COMMON-CONTINUITY'
 if category not in procedures:category='OPERATING-CONTRACT'
 native=('home is absent at process start' in low or 'home is not installed' in low or 'home-managed shared services' in low)
 applicable='Browser required; native equivalence/cross-client gate also retained'
 exception=''
 state='MISSING'
 blocker='No specialist browser runtime/UI registration or authenticated production-equivalent domain API integration verified.'
 if app and owner=='Mini Computer':
  applicable='WEB-EXEMPT; source retained, excluded only from browser implementation denominator'
  state='BLOCKED'; exception='Canonical Web Apps current exemption at 113786–113929 and SH-06 paragraph 1326484: hosted virtualisation/server compute unavailable; re-evaluate if provided.'
  blocker='Required hosted virtualisation/server compute not explicitly provided/approved; no web VM simulation.'
 elif native:
  applicable='Native continuity prerequisite; web counterpart uses authenticated shared services'
  exception='Canonical common apps paragraph 103827 explicitly scopes local Install Home dependency to native clients; browser must not require local Home.'
 elif owner=='Launcher':
  state='BLOCKED'; blocker='Canonical native-only launcher boundary versus global only-MiniComputer exemption unresolved; no browser OS-role simulation or invented exclusion.'
 elif owner=='Terminal' and any(s in low for s in ['pty','execution','shell','ssh','process','scheduled']):
  state='BLOCKED'; blocker='No authorised browser remote/server execution provider/PTY endpoint or scheduling integration verified (canonical 937902).'
 elif 'browser versions' in low or 'capacity targets' in low or 'performance/capacity' in low:
  state='BLOCKED'; blocker='Canonical SH-13 1341108 operational launch decision: supported versions/measured targets unresolved; do not invent support policy.'
 rid=f'B3-{ix}'
 ui,steps=procedures[category]
 api=re.findall(r'9to1\.[A-Za-z][A-Za-z0-9_.]*',text)
 domain=', '.join(dict.fromkeys(api)) if api else app[3] if app else 'Inherited owning-app/shared domain operations; exact implementation mapping pending'
 rows.append(dict(requirement_id=rid,source_revision=manifest['revisionId'],source_start=ix,source_end=p['end'],tab=p['tab'],app=owner,section=h,requirement_level=strength,canonical_clause=text,browser_applicability=applicable,exact_exception_basis=exception,required_ui=ui,actual_browser_ui='MISSING: no running specialist UI/command mapping verified',canonical_domain=domain,existing_source=app[4] if app and app[4] else 'No owning implementation verified',actual_browser_domain='UNVERIFIED: no authenticated endpoint/registration/provider identity verified',test_id=f'{rid}-WEB',procedure_family=category,procedure=steps+' Specific row assertion: '+text,expected_result=text,requirement_state=state,test_outcome='NOT-RUN',evidence='',tested_commit='',frontend_deployment='',backend_identity='',runtime='',fixture='Isolated approved test accounts, seed B3-20261003; populate row-specific entities and record IDs before execution',blocker=blocker))
(out/'requirements.json').write_text(json.dumps(rows,ensure_ascii=False,indent=2)+'\n')
with (out/'requirements.csv').open('w',newline='') as f:
 w=csv.DictWriter(f,fieldnames=list(rows[0]));w.writeheader();w.writerows(rows)
counts=collections.Counter(r['app'] for r in rows)
summary={'source_revision':manifest['revisionId'],'snapshot_sha256':hashlib.sha256((base/'source/canonical.txt').read_bytes()).hexdigest(),'rows':len(rows),'per_scope':dict(counts),'requirement_states':dict(collections.Counter(r['requirement_state'] for r in rows)),'test_outcomes':dict(collections.Counter(r['test_outcome'] for r in rows)),'browser_exempt_rows':sum(r['browser_applicability'].startswith('WEB-EXEMPT') for r in rows),'verified_browser_requirements':0,'coverage_warning':'Source-preserving paragraph coverage is NOT fully reviewed atomic requirement coverage or behavioural acceptance. Compound assertions remain attached to exact clause and require all subcases. Default SHOULD and prose/list/example obligations retained. Independent B6 review required. No actual UI/API route/endpoint is fabricated.','native_home_scope_basis':103827}
(out/'summary.json').write_text(json.dumps(summary,indent=2)+'\n')
md=['# B3 manual acceptance procedures','',f"Canonical revision: `{manifest['revisionId']}`.",'','Each requirements.csv/json row contains the exact source clause, required UI, canonical domain, one test ID and expected content/side-effect assertion. Source-range IDs preserve traceability. All tests are NOT-RUN. Family procedures below are shared setup and interaction steps; the exact row clause is a mandatory additional assertion and compound clauses require every subcase. No browser support policy or performance threshold is invented.','', 'Preconditions: approved non-production deployed frontend/backend identities; exact candidate commit; declared supported browser versions; authorised fixtures/providers; owner/reader/unrelated-account clean profiles; native client for continuity. Missing preconditions block their cases. No real recipient sending, public publishing, paid API expenditure or live charge is implied by this procedure document.','']
for k,(ui,steps) in procedures.items():md += ['## '+k,'','Required UI: '+ui,'',steps,'']
(out/'manual-procedures.md').write_text('\n'.join(md)+'\n')
print(json.dumps(summary,indent=2))
