"""Read-only actual variant generated JNI/typemap/assembly provenance; no native loading."""
import hashlib,json,pathlib,sys,zipfile
variant=sys.argv[1]
if variant not in ('normal','probe'):raise SystemExit('unknown variant')
root=pathlib.Path.cwd();out=root/'artifacts/logs'/('jni-'+variant);out.mkdir(parents=True,exist_ok=True)
def sha(p):
 with p.open('rb') as f:return hashlib.file_digest(f,'sha256').hexdigest()
files=[];textBytes=0;objRoots=[]
# Only per-project exact variant generated roots, never old shared obj/bin or package originals.
for directory in root.rglob('*'):
 if not directory.is_dir() or directory.name not in ('obj','bin') or any(p in ('obj','bin','.git') for p in directory.relative_to(root).parts[:-1]):continue
 objRoots.append(str(directory.relative_to(root)))
 for p in directory.rglob('*'):
  if not p.is_file() or p.is_symlink():continue
  lower=p.name.lower();rel=str(p.relative_to(root))
  selected=(p.name=='AndroidApp.java' or 'typemap' in lower or 'marshal_methods' in lower or 'acw-map' in lower or p.name in ('Haven.dll','AndroidManifest.xml') or ('registration' in lower and p.suffix in ('.cc','.cpp','.ll','.txt')))
  if not selected:continue
  e={'path':rel,'sha256':sha(p),'bytes':p.stat().st_size}
  if p.suffix in ('.java','.xml','.txt','.cc','.cpp','.ll') and p.stat().st_size<=2_097_152 and textBytes+p.stat().st_size<=16_777_216:
   copy=out/'generated-text'/rel;copy.parent.mkdir(parents=True,exist_ok=True);copy.write_bytes(p.read_bytes());textBytes+=p.stat().st_size;e['retainedText']=str(copy.relative_to(root))
  files.append(e)
apkroot=root/'9-1 OS (Android)/src/Haven.Android/bin/Release';apks=list(apkroot.rglob('*-Signed.apk'))
if not apks:apks=list(apkroot.rglob('*.apk'))
archives=[]
for apk in apks:
 entries=[]
 with zipfile.ZipFile(apk) as z:
  for name in z.namelist():
   if name.endswith(('.dex','.dll','.so','.blob','AndroidManifest.xml')):
    with z.open(name) as f:h=hashlib.file_digest(f,'sha256').hexdigest()
    entries.append({'name':name,'sha256':h,'bytes':z.getinfo(name).file_size})
 archives.append({'path':str(apk.relative_to(root)),'sha256':sha(apk),'bytes':apk.stat().st_size,'entries':entries})
receipt={'variant':variant,'actualVariantRoots':objRoots,'generatedFiles':files,'apks':archives,'retainedTextBytes':textBytes,'missingObservations':[kind for kind,match in [('AndroidApp.java',lambda e:e['path'].endswith('/AndroidApp.java')),('typemap',lambda e:'typemap' in e['path'].lower()),('marshal_methods',lambda e:'marshal_methods' in e['path'].lower()),('Haven.dll',lambda e:e['path'].endswith('/Haven.dll'))] if not any(match(e) for e in files)],'qualification':'Actual generated byte/provenance receipts only; missing outputs explicit, no JNI registration/runtime success inferred'}
(out/'generated-receipt.json').write_text(json.dumps(receipt,indent=2)+'\n')
