<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Haven.Android.Cui</RootNamespace>
    <AssemblyName>Haven.Android.Cui</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../framework/CUI/Core/CakeOS.Cui.Core.csproj" />
  </ItemGroup>
</Project>
