// BoardsViewModel bridges the CUI Boards surface and IRichBoardSession.
// It is both the ICuiBindingContext (all {Binding ...} paths in Boards.cui)
// and the ICuiActionDispatcher (all action="..." commands in Boards.cui).
//
// Editing model: static CUI controls use legacy names (BoardTitleBox,
// HeadingBox, ParaBox, Check1Box...); dynamically rendered blocks use
// id-encoded names (t_{blockId}, done_{parentId}_{itemId},
// chk_{parentId}_{itemId}, cell_{blockId}_{r}_{c}, gx_/gv_/gc_ graph fields,
// gvp_ viewport fields, iw_/ialt_ image fields, dvth_/dvcl_ divider fields).
// Control ids generated by the contract never contain '_', so names are split
// on the LAST '_' (documented in BlockRenderer).

using System.ComponentModel;
using System.Runtime.CompilerServices;
using Avalonia.Controls;
using Avalonia.Input;
using CakeOS.Cui;

namespace CakeOS.Apps.Boards.App;

public sealed class BoardsViewModel : ICuiBindingContext, ICuiActionDispatcher, INotifyPropertyChanged
{
    private readonly IRichBoardSession _session;
    private readonly Dictionary<string, object?> _properties = new(StringComparer.OrdinalIgnoreCase);
    private string _selectedSectionId = "section-1";
    private string _selectedPageId = "page-1";
    private string _selectedBlockId = "block-para";
    private bool _syncing;
    private readonly List<Action> _detachers = [];

    public BoardsViewModel(IRichBoardSession session)
    {
        _session = session ?? throw new ArgumentNullException(nameof(session));
        _session.StatusChanged += (_, status) =>
        {
            Set("StatusText", status);
            Set("SaveStateText", MapSaveState(status));
        };
        ReselectDefaults();
        PushDocumentToBindings();
        Set("StatusText", _session.Status);
        Set("SaveStateText", MapSaveState(_session.Status));
    }

    public static string MapSaveState(string status)
    {
        if (string.IsNullOrWhiteSpace(status))
            return "Saved";
        if (status.StartsWith("Saved", StringComparison.OrdinalIgnoreCase))
            return status;
        if (status.Equals("Loaded locally", StringComparison.OrdinalIgnoreCase))
            return "Loaded locally";
        if (status.Contains("fail", StringComparison.OrdinalIgnoreCase))
            return "Save failed";
        if (status.Contains("Saving", StringComparison.OrdinalIgnoreCase))
            return "Saving…";
        return "Unsaved changes";
    }

    public IRichBoardSession Session => _session;

    /// <summary>Raised after structural changes so the host can rebuild BlocksHost (never per keystroke).</summary>
    public event Action? RebuildRequested;

    /// <summary>Raised when the style editor dialog should open (host wires the Window).</summary>
    public event Action? StyleEditorRequested;

    /// <summary>Host-provided file picker: kind is "board", "image" or "attach". Null in headless tests.</summary>
    public Func<string, Task<string?>>? PickFileAsync { get; set; }

    /// <summary>Host-provided board switcher used by OpenBoard when set.</summary>
    public Func<Task>? OpenBoardAsync { get; set; }

    public string SelectedBlockId => _selectedBlockId;
    public IReadOnlyList<RichStyleView> StyleList => _session.Styles;
    public IReadOnlyList<RichBoardBlock> PageBlocks => CurrentPage().Blocks;

    public string InkTool { get; set; } = "Pen";
    public double InkWidth { get; set; } = 2.5;
    public string InkColor { get; set; } = "#FF111111";
    public bool IsDrawMode { get; private set; }
    public double InkZoom { get; set; } = 1;
    public double InkPanX { get; set; }
    public double InkPanY { get; set; }

    public event PropertyChangedEventHandler? PropertyChanged;

    public void Set(string property, object? value, [CallerMemberName] string? caller = null)
    {
        _properties[property] = value;
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(property));
    }

    public object? Get(string property) =>
        _properties.TryGetValue(property, out var val) ? val : null;

    public bool TryGetValue(string path, out object? value)
    {
        var lastDot = path.LastIndexOf('.');
        var key = lastDot >= 0 ? path[(lastDot + 1)..] : path;
        return _properties.TryGetValue(key, out value);
    }

    public string? StyleName(string styleId) =>
        _session.Styles.FirstOrDefault(s => s.Id == styleId)?.Name ?? styleId;

    public RichBoardBlock? FindBlock(string id) =>
        CurrentPage().Blocks.FirstOrDefault(b => b.Id == id);

    public void RequestRebuild() => RebuildRequested?.Invoke();

    public void RequestNavRebuild() => NavRebuildRequested?.Invoke();

    /// <summary>Push bindings, flag dirty and rebuild after a direct view-model edit.</summary>
    public void CommitViewEdit()
    {
        PushDocumentToBindings();
        _session.MarkDirty();
        RequestRebuild();
    }

    public void RefreshAfterEdit()
    {
        PushDocumentToBindings();
        RequestRebuild();
    }

    public async ValueTask DispatchAsync(string command, object? parameter, CancellationToken cancellationToken = default)
    {
        switch (command)
        {
            case "NewBoard":
                NewBoardRequested?.Invoke();
                break;
            case "NewMenu":
                NewMenuRequested?.Invoke();
                break;
            case "OpenBoard":
                await OpenBoardDispatchAsync(cancellationToken);
                break;
            case "SaveBoard":
                Set("SaveStateText", "Saving…");
                await _session.SaveAsync(cancellationToken);
                Set("StatusText", _session.Status);
                Set("SaveStateText", MapSaveState(_session.Status));
                RefreshAfterEdit();
                break;
            case "SaveAsBoard":
                var basePath = _session.FilePath ?? "memory://boards/default";
                var copyPath = basePath.EndsWith(".9to1board", StringComparison.OrdinalIgnoreCase)
                    ? basePath[..^".9to1board".Length] + " (copy).9to1board"
                    : basePath + "-copy";
                await _session.SaveAsAsync(copyPath, cancellationToken);
                PushDocumentToBindings();
                RequestRebuild();
                break;
            case "AddBlock":
                CurrentPage().Blocks.Add(new RichBoardBlock { Kind = "paragraph", Text = "New block" });
                PushDocumentToBindings();
                _session.MarkDirty();
                RequestRebuild();
                break;
            case "AddSection":
                var section = new RichBoardSection { Title = $"Section {_session.Document.Sections.Count + 1}" };
                section.Pages.Add(new RichBoardPage { Title = "New page" });
                _session.Document.Sections.Add(section);
                _selectedSectionId = section.Id;
                _selectedPageId = section.Pages[0].Id;
                SelectExistingBlock(section.Pages[0]);
                SyncSelectedInkView();
                PushDocumentToBindings();
                _session.MarkDirty();
                RequestRebuild();
                break;
            case "AddPage":
                var page = new RichBoardPage { Title = $"Page {CurrentSection().Pages.Count + 1}" };
                CurrentSection().Pages.Add(page);
                _selectedPageId = page.Id;
                SelectExistingBlock(page);
                SyncSelectedInkView();
                PushDocumentToBindings();
                _session.MarkDirty();
                RequestRebuild();
                break;
            case "ToggleBold":
                SelectedBlock().Bold = !SelectedBlock().Bold;
                PushDocumentToBindings();
                _session.MarkDirty();
                RequestRebuild();
                break;
            case "ToggleItalic":
                SelectedBlock().Italic = !SelectedBlock().Italic;
                PushDocumentToBindings();
                _session.MarkDirty();
                RequestRebuild();
                break;
            case "ToggleUnderline":
                SelectedBlock().Underline = !SelectedBlock().Underline;
                PushDocumentToBindings();
                _session.MarkDirty();
                RequestRebuild();
                break;
            case "ToggleStrike":
                SelectedBlock().Strike = !SelectedBlock().Strike;
                PushDocumentToBindings();
                _session.MarkDirty();
                RequestRebuild();
                break;
            case "ToggleSub":
                ToggleBaseline("subscript");
                break;
            case "ToggleSup":
                ToggleBaseline("superscript");
                break;
            case "ClearFormat":
                ClearSelectedFormat();
                break;
            case "FontBigger":
                ScaleSelectedFont(2);
                break;
            case "FontSmaller":
                ScaleSelectedFont(-2);
                break;
            case "AlignLeft": SetSelectedAlignment("left"); break;
            case "AlignCenter": SetSelectedAlignment("center"); break;
            case "AlignRight": SetSelectedAlignment("right"); break;
            case "AlignJustify": SetSelectedAlignment("justify"); break;
            case "IndentInc": ShiftSelectedIndent(1); break;
            case "IndentDec": ShiftSelectedIndent(-1); break;
            case "Undo":
                if (await _session.UndoAsync(cancellationToken))
                    Set("StatusText", _session.Status);
                else
                    Set("StatusText", "Nothing to undo");
                ReselectAfterUndo();
                RefreshAfterEdit();
                break;
            case "Redo":
                if (await _session.RedoAsync(cancellationToken))
                    Set("StatusText", _session.Status);
                else
                    Set("StatusText", "Nothing to redo");
                ReselectAfterUndo();
                RefreshAfterEdit();
                break;
            case "ManageStyles":
                StyleEditorRequested?.Invoke();
                break;
            case "FileMenu":
                FileMenuRequested?.Invoke();
                break;
            case "OverflowMenu":
                OverflowRequested?.Invoke();
                break;
            case "ToggleTheme":
                ThemeToggleRequested?.Invoke();
                break;
            case "AddInkDot":
                AddInkStroke();
                break;
            case "ClearInk":
                await ClearInkAsync(cancellationToken);
                break;
            case "SelectSection1":
                if (_session.Document.Sections.Count > 0)
                {
                    _selectedSectionId = _session.Document.Sections[0].Id;
                    _selectedPageId = CurrentSection().Pages.Count > 0 ? CurrentSection().Pages[0].Id : _selectedPageId;
                    SelectExistingBlock(CurrentPage());
                    SyncSelectedInkView();
                    PushDocumentToBindings();
                    RequestRebuild();
                }
                break;
            case "SelectSection2":
                if (_session.Document.Sections.Count > 1)
                {
                    _selectedSectionId = _session.Document.Sections[1].Id;
                    _selectedPageId = CurrentSection().Pages.Count > 0 ? CurrentSection().Pages[0].Id : _selectedPageId;
                    SelectExistingBlock(CurrentPage());
                    SyncSelectedInkView();
                    PushDocumentToBindings();
                    RequestRebuild();
                }
                break;
            case "SelectPage1":
                if (CurrentSection().Pages.Count > 0)
                {
                    _selectedPageId = CurrentSection().Pages[0].Id;
                    SelectExistingBlock(CurrentPage());
                    SyncSelectedInkView();
                    PushDocumentToBindings();
                    RequestRebuild();
                }
                break;
            case "SelectPage2":
                if (CurrentSection().Pages.Count > 1)
                {
                    _selectedPageId = CurrentSection().Pages[1].Id;
                    SelectExistingBlock(CurrentPage());
                    SyncSelectedInkView();
                    PushDocumentToBindings();
                    RequestRebuild();
                }
                break;
        }
    }

    private async Task OpenBoardDispatchAsync(CancellationToken cancellationToken)
    {
        if (OpenBoardAsync is not null)
        {
            await OpenBoardAsync();
            return;
        }
        var picked = PickFileAsync is not null ? await PickFileAsync("board") : null;
        try
        {
            await _session.OpenAsync(picked ?? _session.FilePath, cancellationToken);
            ReselectDefaults();
            PushDocumentToBindings();
            RequestRebuild();
        }
        catch (Exception error)
        {
            Set("StatusText", "Open failed: " + FirstLine(error.Message));
        }
    }

    /// <summary>
    /// Wire live editing: subscribes to named TextBox/CheckBox controls built
    /// by CuiControlLoader so multiline edits update session state (dirty +
    /// debounced autosave). The loader itself only pushes one-way bindings.
    /// Dynamically rendered BlocksHost children wire their own handlers in
    /// BlockRenderer; this covers the static CUI surface.
    /// </summary>
    public void Attach(Control root)
    {
        foreach (var textBox in FindControls<TextBox>(root))
        {
            var name = textBox.Name ?? string.Empty;
            EventHandler<TextChangedEventArgs> textHandler = (_, _) =>
            {
                if (_syncing)
                    return;
                EditText(name, textBox.Text ?? string.Empty);
            };
            EventHandler<FocusChangedEventArgs> focusHandler = (_, _) =>
            {
                if (_syncing)
                    return;
                FocusBlockFromControl(name);
            };
            textBox.TextChanged += textHandler;
            textBox.GotFocus += focusHandler;
            _detachers.Add(() =>
            {
                textBox.TextChanged -= textHandler;
                textBox.GotFocus -= focusHandler;
            });
        }
        foreach (var checkBox in FindControls<CheckBox>(root))
        {
            var name = checkBox.Name ?? string.Empty;
            EventHandler<Avalonia.Interactivity.RoutedEventArgs> checkHandler = (_, _) =>
            {
                if (_syncing)
                    return;
                EditCheck(name, checkBox.IsChecked == true);
            };
            checkBox.IsCheckedChanged += checkHandler;
            _detachers.Add(() => checkBox.IsCheckedChanged -= checkHandler);
        }
        SyncControlValues(root);
    }

    /// <summary>Unsubscribe all Attach handlers (used when switching boards).</summary>
    public void Detach()
    {
        foreach (var remove in _detachers)
        {
            try { remove(); }
            catch { /* Detach is best-effort. */ }
        }
        _detachers.Clear();
    }

    /// <summary>Push current binding values into live controls without re-firing edits.</summary>
    public void SyncControlValues(Control root)
    {
        _syncing = true;
        try
        {
            foreach (var textBox in FindControls<TextBox>(root))
            {
                var value = Get(BindingForControl(textBox.Name ?? string.Empty))?.ToString();
                if (value is not null && textBox.Text != value)
                    textBox.Text = value;
            }
            foreach (var checkBox in FindControls<CheckBox>(root))
            {
                var value = Get(BindingForControl(checkBox.Name ?? string.Empty))?.ToString();
                if (value is not null && bool.TryParse(value, out var done) && checkBox.IsChecked != done)
                    checkBox.IsChecked = done;
            }
        }
        finally
        {
            _syncing = false;
        }
    }

    public void AddInkStroke(double x = 60, double y = 40)
    {
        if (_session is ContractSessionAdapter adapter)
        {
            _ = CommitSampleInkAsync(adapter, SelectedPageId);
            return;
        }
        _ = CommitInkStrokeAsync(SelectedPageId, [(x, y), (x + 24, y + 16)]);
    }

    /// <summary>Commits one pointer-drawn stroke as real persisted ink data.</summary>
    public async ValueTask CommitInkStrokeAsync(string pageId, IReadOnlyList<(double X, double Y)> points)
    {
        if (_session is ContractSessionAdapter adapter)
        {
            await adapter.CommitInkStrokeAsync(pageId, points);
            PushDocumentToBindings();
            RequestRebuild();
            return;
        }
        AddInkStroke();
    }

    /// <summary>Commits one pressure-aware stroke with the selected tool/width/color.</summary>
    public async ValueTask CommitInkStrokeAsync(
        string pageId,
        IReadOnlyList<(double X, double Y, double Pressure)> points,
        double width, string color, string tool)
    {
        if (_session is ContractSessionAdapter adapter)
        {
            await adapter.CommitInkStrokeAsync(pageId, points, width, color, tool);
            PushDocumentToBindings();
            RequestRebuild();
            return;
        }
        AddInkStroke();
    }

    public async ValueTask ClearInkAsync(CancellationToken cancellationToken = default)
        => await ClearInkAsync(SelectedPageId, cancellationToken);

    public async ValueTask ClearInkAsync(string pageId, CancellationToken cancellationToken = default)
    {
        if (_session is ContractSessionAdapter adapter)
        {
            await adapter.ClearInkAsync(pageId, cancellationToken);
            PushDocumentToBindings();
            RequestRebuild();
            Set("StatusText", _session.Status);
            return;
        }
        RequestRebuild();
    }

    private async Task CommitSampleInkAsync(ContractSessionAdapter adapter, string pageId)
    {
        await adapter.AddSampleInkStrokeAsync(pageId);
        PushDocumentToBindings();
        RequestRebuild();
    }

    // ----- Generalized id-encoded editing (legacy names keep working) -----

    public void EditText(string controlName, string text)
    {
        switch (controlName)
        {
            case "BoardTitleBox":
                _session.Document.Title = text;
                Set("BoardTitle", text);
                break;
            case "NavSearchBox":
                // Filter-only: never dirties the document.
                SearchText = text;
                return;
            case "HeadingBox":
                FindOrCreateBlock("heading").Text = text;
                Set("HeadingText", text);
                break;
            case "ParaBox":
                FindOrCreateBlock("paragraph").Text = text;
                Set("ParaText", text);
                _selectedBlockId = FindOrCreateBlock("paragraph").Id;
                break;
            case "Check1Box":
                FindChecklist(0).Text = text;
                Set("Check1Text", text);
                break;
            case "Check2Box":
                FindChecklist(1).Text = text;
                Set("Check2Text", text);
                break;
            case "Cell00": SetTableCell("0,0", text); Set("Cell00", text); break;
            case "Cell01": SetTableCell("0,1", text); Set("Cell01", text); break;
            case "Cell10": SetTableCell("1,0", text); Set("Cell10", text); break;
            case "Cell11": SetTableCell("1,1", text); Set("Cell11", text); break;
            default:
                if (!EditDynamicText(controlName, text))
                    return;
                break;
        }
        _session.MarkDirty();
    }

    private bool EditDynamicText(string controlName, string text)
    {
        // t_{blockId}: paragraph/heading body.
        if (controlName.StartsWith("t_", StringComparison.Ordinal))
        {
            var block = FindBlock(controlName["t_".Length..]);
            if (block is null)
                return false;
            block.Text = text;
            _selectedBlockId = block.Id;
            PushSelectedInfo();
            return true;
        }
        // chk_{parentId}_{itemId} or chk_{plainId}: checklist item text.
        if (controlName.StartsWith("chk_", StringComparison.Ordinal))
        {
            var block = FindChecklistBlock(controlName["chk_".Length..]);
            if (block is null)
                return false;
            block.Text = text;
            _selectedBlockId = block.Id;
            return true;
        }
        // cell_{blockId}_{r}_{c}: table cell text.
        if (controlName.StartsWith("cell_", StringComparison.Ordinal))
        {
            var rest = controlName["cell_".Length..].Split('_');
            if (rest.Length < 3 || !int.TryParse(rest[^2], out var row) || !int.TryParse(rest[^1], out var col))
                return false;
            var blockId = string.Join("_", rest[..^2]);
            var block = FindBlock(blockId);
            if (block is null || block.Kind != "table")
                return false;
            block.TableCells[$"{row},{col}"] = text;
            _selectedBlockId = block.Id;
            return true;
        }
        // gx_{blockId}_{exprId}: graph expression text.
        if (controlName.StartsWith("gx_", StringComparison.Ordinal))
        {
            if (!SplitBlockAndTail(controlName["gx_".Length..], out var blockId, out var exprId))
                return false;
            var expr = FindBlock(blockId)?.Graph?.Expressions.FirstOrDefault(e => e.Id == exprId);
            if (expr is null)
                return false;
            expr.Text = text;
            _selectedBlockId = blockId;
            return true;
        }
        // gc_{blockId}_{exprId}: graph expression color.
        if (controlName.StartsWith("gc_", StringComparison.Ordinal))
        {
            if (!SplitBlockAndTail(controlName["gc_".Length..], out var blockId, out var exprId))
                return false;
            var expr = FindBlock(blockId)?.Graph?.Expressions.FirstOrDefault(e => e.Id == exprId);
            if (expr is null)
                return false;
            expr.Color = text;
            return true;
        }
        // gvp_{field}_{blockId}: graph viewport doubles.
        if (controlName.StartsWith("gvp_", StringComparison.Ordinal))
            return EditViewportField(controlName["gvp_".Length..], text);
        // iw_{blockId} / ialt_{blockId}: image width / alt text.
        if (controlName.StartsWith("iw_", StringComparison.Ordinal))
        {
            var block = FindBlock(controlName["iw_".Length..]);
            if (block?.Image is null)
                return false;
            if (double.TryParse(text, out var width) && width is >= 0 and <= 8000)
                block.Image.Width = width;
            return true;
        }
        if (controlName.StartsWith("ialt_", StringComparison.Ordinal))
        {
            var block = FindBlock(controlName["ialt_".Length..]);
            if (block?.Image is null)
                return false;
            block.Image.AltText = text;
            return true;
        }
        // dvth_{blockId} / dvcl_{blockId}: divider thickness / color.
        if (controlName.StartsWith("dvth_", StringComparison.Ordinal))
        {
            var block = FindBlock(controlName["dvth_".Length..]);
            if (block?.Divider is null)
                return false;
            if (double.TryParse(text, out var thickness) && thickness is > 0 and <= 64)
                block.Divider.Thickness = thickness;
            return true;
        }
        if (controlName.StartsWith("dvcl_", StringComparison.Ordinal))
        {
            var block = FindBlock(controlName["dvcl_".Length..]);
            if (block?.Divider is null)
                return false;
            block.Divider.Color = text;
            return true;
        }
        // inkwidth / inkcolor: session-level ink defaults (static names).
        if (controlName == "InkWidthBox")
        {
            if (double.TryParse(text, out var width) && width is > 0 and <= 64)
                InkWidth = width;
            return true;
        }
        if (controlName == "InkColorBox")
        {
            if (!string.IsNullOrWhiteSpace(text))
                InkColor = text.Trim();
            return true;
        }
        return false;
    }

    private bool EditViewportField(string rest, string text)
    {
        // rest = {field}_{blockId}; block ids never contain '_' from the contract.
        var cut = rest.LastIndexOf('_');
        if (cut <= 0)
            return false;
        var field = rest[..cut];
        var blockId = rest[(cut + 1)..];
        var graph = FindBlock(blockId)?.Graph;
        if (graph is null || !double.TryParse(text, out var value) || !double.IsFinite(value))
            return false;
        switch (field.ToLowerInvariant())
        {
            case "xmin": graph.XMin = value; break;
            case "xmax": graph.XMax = value; break;
            case "ymin": graph.YMin = value; break;
            case "ymax": graph.YMax = value; break;
            default: return false;
        }
        _selectedBlockId = blockId;
        return true;
    }

    public void EditCheck(string controlName, bool done)
    {
        switch (controlName)
        {
            case "Check1Done": FindChecklist(0).IsChecked = done; Set("Check1Done", done); break;
            case "Check2Done": FindChecklist(1).IsChecked = done; Set("Check2Done", done); break;
            default:
                if (!EditDynamicCheck(controlName, done))
                    return;
                break;
        }
        _session.MarkDirty();
    }

    private bool EditDynamicCheck(string controlName, bool done)
    {
        // done_{parentId}_{itemId} or done_{plainId}.
        if (controlName.StartsWith("done_", StringComparison.Ordinal))
        {
            var block = FindChecklistBlock(controlName["done_".Length..]);
            if (block is null)
                return false;
            block.IsChecked = done;
            _selectedBlockId = block.Id;
            return true;
        }
        // gv_{blockId}_{exprId}: graph expression visibility.
        if (controlName.StartsWith("gv_", StringComparison.Ordinal))
        {
            if (!SplitBlockAndTail(controlName["gv_".Length..], out var blockId, out var exprId))
                return false;
            var expr = FindBlock(blockId)?.Graph?.Expressions.FirstOrDefault(e => e.Id == exprId);
            if (expr is null)
                return false;
            expr.Visible = done;
            _selectedBlockId = blockId;
            return true;
        }
        return false;
    }

    public void FocusBlock(string blockId)
    {
        if (FindBlock(blockId) is null)
            return;
        if (_selectedBlockId == blockId)
            return;
        _selectedBlockId = blockId;
        PushSelectedInfo();
        SelectionChanged?.Invoke();
    }

    // ----- Product navigation / selection / menus (visual pass) -----

    /// <summary>Raised when block/section/page selection changes (context UI refresh, no editor rebuild).</summary>
    public event Action? SelectionChanged;

    /// <summary>Raised when the navigation pane alone should rebuild (search, rename, reorder).</summary>
    public event Action? NavRebuildRequested;

    /// <summary>Raised when the File menu should open (host builds it).</summary>
    public event Action? FileMenuRequested;

    /// <summary>Raised when the host should create a separate local board document.</summary>
    public event Action? NewBoardRequested;

    /// <summary>Raised when the host should open the in-page + New menu.</summary>
    public event Action? NewMenuRequested;

    /// <summary>Raised when the overflow menu should open (host builds it).</summary>
    public event Action? OverflowRequested;

    /// <summary>Raised when the theme toggle is invoked (host re-applies chrome).</summary>
    public event Action? ThemeToggleRequested;

    public string SelectedSectionId => _selectedSectionId;
    public string SelectedPageId => _selectedPageId;

    private string _searchText = string.Empty;

    /// <summary>Navigation filter text; setting it rebuilds only the nav pane.</summary>
    public string SearchText
    {
        get => _searchText;
        set
        {
            if (_searchText == value)
                return;
            _searchText = value ?? string.Empty;
            NavRebuildRequested?.Invoke();
        }
    }

    public void SelectSection(string sectionId)
    {
        var section = _session.Document.Sections.FirstOrDefault(s => s.Id == sectionId);
        if (section is null)
            return;
        _selectedSectionId = section.Id;
        var page = section.Pages.FirstOrDefault();
        _selectedPageId = page?.Id ?? _selectedPageId;
        if (page is not null)
            SelectExistingBlock(page);
        SyncSelectedInkView();
        PushDocumentToBindings();
        NavRebuildRequested?.Invoke();
        SelectionChanged?.Invoke();
        RequestRebuild();
    }

    public void SelectPage(string sectionId, string pageId)
    {
        var section = _session.Document.Sections.FirstOrDefault(s => s.Id == sectionId);
        var page = section?.Pages.FirstOrDefault(p => p.Id == pageId);
        if (section is null || page is null)
            return;
        _selectedSectionId = section.Id;
        _selectedPageId = page.Id;
        SelectExistingBlock(page);
        SyncSelectedInkView();
        PushDocumentToBindings();
        NavRebuildRequested?.Invoke();
        SelectionChanged?.Invoke();
        RequestRebuild();
    }

    public void RenameSection(string sectionId, string title)
    {
        var section = _session.Document.Sections.FirstOrDefault(s => s.Id == sectionId);
        if (section is null)
            return;
        section.Title = string.IsNullOrWhiteSpace(title) ? "Untitled section" : title.Trim();
        PushDocumentToBindings();
        _session.MarkDirty();
        NavRebuildRequested?.Invoke();
    }

    public void RenamePage(string sectionId, string pageId, string title)
    {
        var page = _session.Document.Sections
            .FirstOrDefault(s => s.Id == sectionId)?.Pages.FirstOrDefault(p => p.Id == pageId);
        if (page is null)
            return;
        page.Title = string.IsNullOrWhiteSpace(title) ? "Untitled page" : title.Trim();
        PushDocumentToBindings();
        _session.MarkDirty();
        NavRebuildRequested?.Invoke();
        RequestRebuild();
    }

    public async Task DeleteSectionAsync(string sectionId)
    {
        if (_session is ContractSessionAdapter adapter)
        {
            if (!await adapter.DeleteSectionAsync(sectionId))
            {
                Set("StatusText", "The final section cannot be deleted");
                return;
            }
            ReselectAfterNavChange();
            RefreshAfterEdit();
            NavRebuildRequested?.Invoke();
            return;
        }
        var removed = _session.Document.Sections.Count > 1 &&
            _session.Document.Sections.RemoveAll(s => s.Id == sectionId) > 0;
        if (!removed)
        {
            Set("StatusText", "The final section cannot be deleted");
            return;
        }
        ReselectAfterNavChange();
        PushDocumentToBindings();
        _session.MarkDirty();
        RequestRebuild();
        NavRebuildRequested?.Invoke();
    }

    public async Task DeletePageAsync(string sectionId, string pageId)
    {
        if (_session is ContractSessionAdapter adapter)
        {
            if (!await adapter.DeletePageAsync(pageId))
            {
                Set("StatusText", "The final page cannot be deleted");
                return;
            }
            ReselectAfterNavChange();
            RefreshAfterEdit();
            NavRebuildRequested?.Invoke();
            return;
        }
        var section = _session.Document.Sections.FirstOrDefault(s => s.Id == sectionId);
        var removed = section is not null && section.Pages.Count > 1 &&
            section.Pages.RemoveAll(p => p.Id == pageId) > 0;
        if (!removed)
        {
            Set("StatusText", "The final page cannot be deleted");
            return;
        }
        ReselectAfterNavChange();
        PushDocumentToBindings();
        _session.MarkDirty();
        RequestRebuild();
        NavRebuildRequested?.Invoke();
    }

    public async Task DuplicateSectionAsync(string sectionId)
    {
        string? freshId = null;
        if (_session is ContractSessionAdapter adapter)
        {
            freshId = await adapter.DuplicateSectionAsync(sectionId);
            RefreshAfterEdit();
        }
        else
        {
            var source = _session.Document.Sections.FirstOrDefault(s => s.Id == sectionId);
            if (source is null)
                return;
            var copy = CloneSection(source);
            _session.Document.Sections.Insert(_session.Document.Sections.IndexOf(source) + 1, copy);
            freshId = copy.Id;
            PushDocumentToBindings();
            _session.MarkDirty();
            RequestRebuild();
        }
        if (freshId is not null)
        {
            _selectedSectionId = freshId;
            ReselectAfterNavChange();
        }
        NavRebuildRequested?.Invoke();
    }

    public async Task DuplicatePageAsync(string sectionId, string pageId)
    {
        string? freshId = null;
        if (_session is ContractSessionAdapter adapter)
        {
            freshId = await adapter.DuplicatePageAsync(pageId);
            RefreshAfterEdit();
        }
        else
        {
            var section = _session.Document.Sections.FirstOrDefault(s => s.Id == sectionId);
            var source = section?.Pages.FirstOrDefault(p => p.Id == pageId);
            if (section is null || source is null)
                return;
            var copy = ClonePage(source);
            section.Pages.Add(copy);
            freshId = copy.Id;
            PushDocumentToBindings();
            _session.MarkDirty();
            RequestRebuild();
        }
        if (freshId is not null)
        {
            _selectedPageId = freshId;
            ReselectAfterNavChange();
        }
        NavRebuildRequested?.Invoke();
    }

    public async Task MoveSectionAsync(string sectionId, int delta)
    {
        var sections = _session.Document.Sections;
        var index = sections.FindIndex(s => s.Id == sectionId);
        if (index < 0)
            return;
        var target = Math.Clamp(index + delta, 0, sections.Count - 1);
        if (target == index)
            return;
        if (_session is ContractSessionAdapter adapter)
        {
            await adapter.MoveSectionAsync(sectionId, target);
            RefreshAfterEdit();
        }
        else
        {
            var section = sections[index];
            sections.RemoveAt(index);
            sections.Insert(target, section);
            PushDocumentToBindings();
            _session.MarkDirty();
            RequestRebuild();
        }
        NavRebuildRequested?.Invoke();
    }

    public async Task MovePageAsync(string sectionId, string pageId, int delta)
    {
        var section = _session.Document.Sections.FirstOrDefault(s => s.Id == sectionId);
        if (section is null)
            return;
        var index = section.Pages.FindIndex(p => p.Id == pageId);
        if (index < 0)
            return;
        var target = Math.Clamp(index + delta, 0, section.Pages.Count - 1);
        if (target == index)
            return;
        if (_session is ContractSessionAdapter adapter)
        {
            await adapter.MovePageAsync(pageId, sectionId, target);
            RefreshAfterEdit();
        }
        else
        {
            var page = section.Pages[index];
            section.Pages.RemoveAt(index);
            section.Pages.Insert(target, page);
            PushDocumentToBindings();
            _session.MarkDirty();
            RequestRebuild();
        }
        NavRebuildRequested?.Invoke();
    }

    /// <summary>Converts the selected text block between paragraph/heading/list kinds.</summary>
    public async Task ConvertSelectedKindAsync(string kind)
    {
        var block = SelectedBlockOrNull();
        if (block is null)
            return;
        var contractKind = kind switch
        {
            "heading" => CakeOS.Apps.Boards.Contract.HavenRichBlockKind.Heading,
            "checklist" => CakeOS.Apps.Boards.Contract.HavenRichBlockKind.Checklist,
            "bulleted" => CakeOS.Apps.Boards.Contract.HavenRichBlockKind.BulletList,
            "numbered" => CakeOS.Apps.Boards.Contract.HavenRichBlockKind.NumberedList,
            _ => CakeOS.Apps.Boards.Contract.HavenRichBlockKind.Paragraph,
        };
        if (_session is ContractSessionAdapter adapter)
        {
            await adapter.ConvertBlockKindAsync(CurrentPage().Id, block.Id, contractKind);
            RefreshAfterEdit();
            return;
        }
        block.Kind = kind switch
        {
            "heading" => "heading",
            "checklist" or "bulleted" or "numbered" => "checklist",
            _ => "paragraph",
        };
        PushDocumentToBindings();
        _session.MarkDirty();
        RequestRebuild();
    }

    public (string Title, string FileName, string Path, long SizeBytes) BoardInfo()
    {
        var path = _session.FilePath ?? string.Empty;
        var size = 0L;
        try
        {
            if (!string.IsNullOrEmpty(path) && File.Exists(path))
                size = new FileInfo(path).Length;
        }
        catch (IOException) { }
        catch (UnauthorizedAccessException) { }
        return (_session.Document.Title, SafeFileName(path), path, size);
    }

    private static string SafeFileName(string path)
    {
        try
        {
            return string.IsNullOrEmpty(path) ? "Unsaved board" : Path.GetFileName(path);
        }
        catch (ArgumentException)
        {
            return "Unsaved board";
        }
    }

    private void ReselectAfterNavChange()
    {
        var firstSection = _session.Document.Sections.FirstOrDefault();
        if (firstSection is null)
            return;
        if (!_session.Document.Sections.Any(s => s.Id == _selectedSectionId))
            _selectedSectionId = firstSection.Id;
        var section = _session.Document.Sections.First(s => s.Id == _selectedSectionId);
        if (!section.Pages.Any(p => p.Id == _selectedPageId))
            _selectedPageId = section.Pages.FirstOrDefault()?.Id ?? _selectedPageId;
        SelectExistingBlock(CurrentPage());
        SyncSelectedInkView();
    }

    private RichBoardBlock? SelectedBlockOrNull()
    {
        var page = CurrentPage();
        return page.Blocks.FirstOrDefault(b => b.Id == _selectedBlockId)
            ?? page.Blocks.FirstOrDefault();
    }

    private static RichBoardSection CloneSection(RichBoardSection source)
    {
        var json = System.Text.Json.JsonSerializer.Serialize(source);
        var copy = System.Text.Json.JsonSerializer.Deserialize<RichBoardSection>(json) ?? new RichBoardSection();
        copy.Id = Guid.NewGuid().ToString("N");
        copy.Title = source.Title + " copy";
        foreach (var page in copy.Pages)
            FreshPageCloneIds(page);
        return copy;
    }

    private static RichBoardPage ClonePage(RichBoardPage source)
    {
        var json = System.Text.Json.JsonSerializer.Serialize(source);
        var copy = System.Text.Json.JsonSerializer.Deserialize<RichBoardPage>(json) ?? new RichBoardPage();
        FreshPageCloneIds(copy);
        copy.Title = source.Title + " copy";
        return copy;
    }

    private static void FreshPageCloneIds(RichBoardPage page)
    {
        page.Id = Guid.NewGuid().ToString("N");
        foreach (var block in page.Blocks)
        {
            var parts = block.Id.Split(':');
            block.Id = parts.Length > 1
                ? parts[0] + ":" + Guid.NewGuid().ToString("N")
                : Guid.NewGuid().ToString("N");
        }
    }

    private void FocusBlockFromControl(string controlName)
    {
        var legacy = controlName switch
        {
            "HeadingBox" => FindOrCreateBlock("heading").Id,
            "ParaBox" => FindOrCreateBlock("paragraph").Id,
            "Check1Box" or "Check1Done" => FindChecklist(0).Id,
            "Check2Box" or "Check2Done" => FindChecklist(1).Id,
            "Cell00" or "Cell01" or "Cell10" or "Cell11" => FindOrCreateBlock("table").Id,
            _ => null,
        };
        if (legacy is not null)
        {
            FocusBlock(legacy);
            return;
        }
        if (controlName.StartsWith("t_", StringComparison.Ordinal))
            FocusBlock(controlName["t_".Length..]);
        else if (controlName.StartsWith("chk_", StringComparison.Ordinal)
            || controlName.StartsWith("done_", StringComparison.Ordinal))
        {
            var tail = controlName[(controlName.IndexOf('_') + 1)..];
            var block = FindChecklistBlock(tail);
            if (block is not null)
                FocusBlock(block.Id);
        }
        else if (controlName.StartsWith("cell_", StringComparison.Ordinal))
        {
            var rest = controlName["cell_".Length..].Split('_');
            if (rest.Length >= 3 &&
                int.TryParse(rest[^2], out var row) && int.TryParse(rest[^1], out var col))
            {
                FocusBlock(string.Join("_", rest[..^2]));
                SelectedCell = (string.Join("_", rest[..^2]), row, col);
                SelectionChanged?.Invoke();
            }
        }
    }

    /// <summary>Currently focused table cell, if any (block id, row, column).</summary>
    public (string BlockId, int Row, int Col)? SelectedCell { get; private set; }

    // ----- Block operations used by BlockRenderer -----

    public async Task InsertKindAsync(string kindTag, string? insertAfterBlockId = null)
    {
        // Drawing is a page capability, not a hidden placeholder block. The
        // renderer provides its surface only while drawing is active or real
        // strokes already exist, so an empty page does not acquire dead space.
        if (string.Equals(kindTag, "ink", StringComparison.OrdinalIgnoreCase))
        {
            await ActivateDrawingAsync();
            return;
        }
        if (string.Equals(kindTag, "freeform", StringComparison.OrdinalIgnoreCase))
        {
            await AddCanvasBoxAsync();
            return;
        }
        string? attachmentPath = null;
        if (string.Equals(kindTag, "attachment", StringComparison.OrdinalIgnoreCase))
        {
            if (PickFileAsync is null)
            {
                Set("StatusText", "Attachment pick needs the desktop host");
                return;
            }
            var targetSectionId = SelectedSectionId;
            var targetPageId = SelectedPageId;
            attachmentPath = await PickFileAsync("attach");
            if (SelectedSectionId != targetSectionId || SelectedPageId != targetPageId)
            {
                Set("StatusText", "The page changed while choosing an attachment. Choose a note and try again.");
                return;
            }
            if (string.IsNullOrWhiteSpace(attachmentPath) || !File.Exists(attachmentPath))
                return;
        }
        RichStyleView? insertionStyle = null;
        if (kindTag.StartsWith("style:", StringComparison.Ordinal))
        {
            var styleId = kindTag["style:".Length..];
            insertionStyle = StyleList.FirstOrDefault(candidate => candidate.Id == styleId);
            if (insertionStyle is null)
            {
                Set("StatusText", $"Style '{styleId}' was not found");
                return;
            }
            if (insertAfterBlockId is null)
            {
                await ApplyStyleToSelectedAsync(styleId);
                return;
            }
        }
        var page = CurrentPage();
        RichBoardBlock block;
        if (insertionStyle is not null)
        {
            block = new RichBoardBlock
            {
                Kind = insertionStyle.BlockKind == "heading" ? "heading" : "paragraph",
                Text = insertionStyle.BlockKind == "heading" ? "New heading" : "New paragraph",
                StyleId = insertionStyle.Id,
            };
        }
        else
        {
            block = kindTag switch
            {
                "paragraph" => new RichBoardBlock { Kind = "paragraph", Text = "New paragraph" },
                "heading" => new RichBoardBlock { Kind = "heading", Text = "New heading" },
                "checklist" => new RichBoardBlock { Kind = "checklist", Text = "New item" },
                "bulleted" => new RichBoardBlock { Kind = "bulleted", Text = "New item" },
                "numbered" => new RichBoardBlock { Kind = "numbered", Text = "New item" },
                "table" => new RichBoardBlock
                {
                    Kind = "table", Text = "New table", TableRows = 2, TableCols = 2,
                    TableCells = new Dictionary<string, string>(StringComparer.Ordinal)
                    {
                        ["0,0"] = string.Empty, ["0,1"] = string.Empty,
                        ["1,0"] = string.Empty, ["1,1"] = string.Empty,
                    },
                },
                "image" => new RichBoardBlock
                {
                    Kind = "image", Text = "image",
                    Image = new RichImageView { DisplayName = "image (choose a file)", MediaType = "image/png" },
                },
                "divider" => new RichBoardBlock
                {
                    Kind = "divider",
                    Divider = new RichDividerView { Thickness = 1, LineStyle = "solid", Color = "#FF5F6368" },
                },
                "graph" => new RichBoardBlock
                {
                    Kind = "graph",
                    Graph = new RichGraphView
                    {
                        Expressions = [new RichGraphExpressionView { Text = "y = x" }],
                        XMin = -10, XMax = 10, YMin = -10, YMax = 10,
                    },
                },
                _ => new RichBoardBlock { Kind = "paragraph", Text = "New block" },
            };
        }
        var insertionAnchor = insertAfterBlockId ?? _selectedBlockId;
        var selectedIndex = page.Blocks.FindIndex(item => item.Id == insertionAnchor);
        if (insertAfterBlockId is not null && selectedIndex < 0)
        {
            Set("StatusText", "The insertion point is no longer on this page. Choose a note and try again.");
            return;
        }
        if (selectedIndex >= 0)
            page.Blocks.Insert(selectedIndex + 1, block);
        else
            page.Blocks.Add(block);
        _selectedBlockId = block.Id;
        PushDocumentToBindings();
        _session.MarkDirty();
        if (kindTag == "image")
            Set("StatusText", "Image block added — use Replace to choose a file");
        RequestRebuild();
        if (kindTag == "image")
            await ReplaceImageAsync(block.Id);
        else if (kindTag == "attachment")
            await AttachFileAsync(block.Id, attachmentPath);
    }

    public async Task ApplyStyleToSelectedAsync(string styleId)
    {
        if (string.IsNullOrWhiteSpace(styleId))
            return;
        if (!_session.Styles.Any(s => s.Id == styleId))
        {
            Set("StatusText", $"Style '{styleId}' was not found");
            return;
        }
        SelectedBlock().StyleId = styleId;
        PushDocumentToBindings();
        _session.MarkDirty();
        RequestRebuild();
    }

    public async Task DeleteBlockAsync(string viewBlockId)
    {
        if (_session is ContractSessionAdapter adapter)
        {
            await adapter.DeleteViewBlockAsync(CurrentPage().Id, viewBlockId);
            ReselectAfterUndo();
            RefreshAfterEdit();
            return;
        }
        var page = CurrentPage();
        var removed = page.Blocks.RemoveAll(b => b.Id == viewBlockId);
        if (removed == 0)
        {
            Set("StatusText", "Block was not found");
            return;
        }
        ReselectAfterUndo();
        PushDocumentToBindings();
        _session.MarkDirty();
        RequestRebuild();
    }

    public async Task AddChecklistItemAsync(string parentViewBlockId, string text = "New item")
    {
        var (parentId, _) = SplitItemId(parentViewBlockId);
        if (_session is ContractSessionAdapter adapter && parentId is not null)
        {
            // Targeted parent insert through the adapter (merge would use the first list).
            await adapter.AddChecklistItemAsync(CurrentPage().Id, parentId, text);
            RefreshAfterEdit();
            return;
        }
        CurrentPage().Blocks.Add(new RichBoardBlock { Kind = "checklist", Text = text });
        PushDocumentToBindings();
        _session.MarkDirty();
        RequestRebuild();
    }

    /// <summary>Enter at the end of a checklist row appends the next item.</summary>
    public async Task ChecklistEnterAsync(string viewBlockId)
    {
        var block = FindChecklistBlock(viewBlockId);
        var parentKey = block is not null ? ParentKey(block.Id) : viewBlockId;
        await AddChecklistItemAsync(parentKey);
    }

    /// <summary>Backspace on an empty checklist row removes it.</summary>
    public async Task ChecklistBackspaceAsync(string viewBlockId, string currentText)
    {
        if (!string.IsNullOrEmpty(currentText))
            return;
        var block = FindChecklistBlock(viewBlockId);
        if (block is null)
            return;
        // Never delete the final checklist row; clear it instead.
        if (CurrentPage().Blocks.Count(b => b.Kind == "checklist") <= 1)
        {
            block.Text = string.Empty;
            PushDocumentToBindings();
            _session.MarkDirty();
            RequestRebuild();
            return;
        }
        await DeleteBlockAsync(block.Id);
    }

    public void ChecklistIndent(string viewBlockId, int delta)
    {
        var block = FindChecklistBlock(viewBlockId);
        if (block is null)
            return;
        block.Level = Math.Clamp(block.Level + delta, 0, 8);
        PushDocumentToBindings();
        _session.MarkDirty();
    }

    public void TableAddRow(string blockId)
    {
        var block = FindBlock(blockId);
        if (block is null || block.Kind != "table")
            return;
        EnsureTableDims(block);
        block.TableRows = Math.Min(100, block.TableRows + 1);
        PushDocumentToBindings();
        _session.MarkDirty();
        RequestRebuild();
    }

    public void TableDelRow(string blockId)
    {
        var block = FindBlock(blockId);
        if (block is null || block.Kind != "table")
            return;
        EnsureTableDims(block);
        if (block.TableRows <= 1)
            return;
        block.TableRows--;
        var doomed = block.TableCells.Keys.Where(k => RowOf(k) >= block.TableRows).ToArray();
        foreach (var key in doomed)
            block.TableCells.Remove(key);
        var doomedStyles = block.CellStyles.Keys.Where(k => RowOf(k) >= block.TableRows).ToArray();
        foreach (var key in doomedStyles)
            block.CellStyles.Remove(key);
        PushDocumentToBindings();
        _session.MarkDirty();
        RequestRebuild();
    }

    public void TableAddCol(string blockId)
    {
        var block = FindBlock(blockId);
        if (block is null || block.Kind != "table")
            return;
        EnsureTableDims(block);
        block.TableCols = Math.Min(50, block.TableCols + 1);
        PushDocumentToBindings();
        _session.MarkDirty();
        RequestRebuild();
    }

    public void TableDelCol(string blockId)
    {
        var block = FindBlock(blockId);
        if (block is null || block.Kind != "table")
            return;
        EnsureTableDims(block);
        if (block.TableCols <= 1)
            return;
        block.TableCols--;
        var doomed = block.TableCells.Keys.Where(k => ColOf(k) >= block.TableCols).ToArray();
        foreach (var key in doomed)
            block.TableCells.Remove(key);
        var doomedStyles = block.CellStyles.Keys.Where(k => ColOf(k) >= block.TableCols).ToArray();
        foreach (var key in doomedStyles)
            block.CellStyles.Remove(key);
        PushDocumentToBindings();
        _session.MarkDirty();
        RequestRebuild();
    }

    public void SetCellAlign(string blockId, int row, int col, string alignH)
    {
        var block = FindBlock(blockId);
        if (block is null || block.Kind != "table")
            return;
        var style = block.CellStyles.TryGetValue($"{row},{col}", out var existing)
            ? existing
            : block.CellStyles[$"{row},{col}"] = new RichCellStyleView();
        style.AlignH = alignH;
        _session.MarkDirty();
    }

    public void ToggleCellBold(string blockId, int row, int col)
    {
        var block = FindBlock(blockId);
        if (block is null || block.Kind != "table")
            return;
        var style = block.CellStyles.TryGetValue($"{row},{col}", out var existing)
            ? existing
            : block.CellStyles[$"{row},{col}"] = new RichCellStyleView();
        style.Bold = !style.Bold;
        PushDocumentToBindings();
        _session.MarkDirty();
        RequestRebuild();
    }

    public void ToggleGraphExpression(string blockId, string exprId)
    {
        var expr = FindBlock(blockId)?.Graph?.Expressions.FirstOrDefault(e => e.Id == exprId);
        if (expr is null)
            return;
        expr.Visible = !expr.Visible;
        PushDocumentToBindings();
        _session.MarkDirty();
        RequestRebuild();
    }

    public void GraphAddExpression(string blockId, string text = "y = x")
    {
        var graph = FindBlock(blockId)?.Graph;
        if (graph is null || graph.Expressions.Count >= 32)
            return;
        graph.Expressions.Add(new RichGraphExpressionView { Text = text });
        PushDocumentToBindings();
        _session.MarkDirty();
        RequestRebuild();
    }

    public async Task GraphDeleteExpressionAsync(string blockId, string exprId)
    {
        var graph = FindBlock(blockId)?.Graph;
        if (graph is null)
            return;
        graph.Expressions.RemoveAll(e => e.Id == exprId);
        if (graph.Expressions.Count == 0)
            graph.Expressions.Add(new RichGraphExpressionView { Text = "y = x" });
        PushDocumentToBindings();
        _session.MarkDirty();
        RequestRebuild();
        await Task.CompletedTask;
    }

    public void GraphPanZoom(string blockId, double dx, double dy, double factor)
    {
        var graph = FindBlock(blockId)?.Graph;
        if (graph is null)
            return;
        var width = graph.XMax - graph.XMin;
        var height = graph.YMax - graph.YMin;
        if (factor != 1)
        {
            width /= factor;
            height /= factor;
            var cx = (graph.XMin + graph.XMax) / 2;
            var cy = (graph.YMin + graph.YMax) / 2;
            graph.XMin = cx - width / 2;
            graph.XMax = cx + width / 2;
            graph.YMin = cy - height / 2;
            graph.YMax = cy + height / 2;
        }
        if (dx != 0 || dy != 0)
        {
            graph.XMin += dx * width;
            graph.XMax += dx * width;
            graph.YMin += dy * height;
            graph.YMax += dy * height;
        }
        PushDocumentToBindings();
        _session.MarkDirty();
        RequestRebuild();
    }

    private readonly Dictionary<string, (long Version, byte[] Bytes)> _imageBytesCache = new(StringComparer.Ordinal);

    /// <summary>Embedded image bytes without file IO (sidecars need the async path).</summary>
    public byte[]? TryResolveImageBytes(string blockId)
    {
        if (_session is ContractSessionAdapter adapter)
        {
            var version = adapter.DocumentVersion;
            if (_imageBytesCache.TryGetValue(blockId, out var cached) && cached.Version == version)
                return cached.Bytes;
            var bytes = adapter.TryGetEmbeddedImageBytes(blockId);
            if (bytes is not null)
                _imageBytesCache[blockId] = (version, bytes);
            return bytes;
        }
        var view = FindBlock(blockId)?.Image?.DataBase64;
        if (string.IsNullOrEmpty(view))
            return null;
        try
        {
            return Convert.FromBase64String(view);
        }
        catch (FormatException)
        {
            return null;
        }
    }

    /// <summary>Display bytes for an image block, resolved from the contract (never stored in the view).</summary>
    public async Task<byte[]?> ResolveImageBytesAsync(string blockId)
    {
        var immediate = TryResolveImageBytes(blockId);
        if (immediate is not null)
            return immediate;
        if (_session is ContractSessionAdapter adapter)
        {
            var bytes = await adapter.GetImageBytesAsync(blockId);
            if (bytes is not null)
                _imageBytesCache[blockId] = (adapter.DocumentVersion, bytes);
            return bytes;
        }
        return null;
    }

    public async Task ReplaceImageAsync(string blockId)
    {
        var block = FindBlock(blockId);
        if (block is null || (block.Kind != "image" && block.Kind != "paragraph" && block.Kind != "heading"))
            return;
        if (PickFileAsync is null)
        {
            Set("StatusText", "Image pick needs the desktop host");
            return;
        }
        var path = await PickFileAsync("image");
        if (string.IsNullOrWhiteSpace(path) || !File.Exists(path))
            return;
        var bytes = await File.ReadAllBytesAsync(path);
        var mediaType = Path.GetExtension(path).ToLowerInvariant() switch
        {
            ".jpg" or ".jpeg" => "image/jpeg",
            ".gif" => "image/gif",
            ".bmp" => "image/bmp",
            ".webp" => "image/webp",
            _ => "image/png",
        };
        var target = block.Kind == "image" ? block : ConvertToImageBlock(block);
        target.Image = new RichImageView
        {
            DisplayName = Path.GetFileName(path),
            MediaType = mediaType,
            DataBase64 = Convert.ToBase64String(bytes),
            Width = target.Image?.Width ?? 0,
            Alignment = target.Image?.Alignment ?? "inherit",
            AltText = target.Image?.AltText ?? string.Empty,
        };
        target.Text = target.Image.DisplayName;
        PushDocumentToBindings();
        _session.MarkDirty();
        RequestRebuild();
    }

    public async Task AttachFileAsync(string blockId, string? pickedPath = null)
    {
        var block = FindBlock(blockId);
        if (block is null)
            return;
        if (pickedPath is null && PickFileAsync is null)
        {
            Set("StatusText", "Attachment pick needs the desktop host");
            return;
        }
        var path = pickedPath ?? await PickFileAsync!("attach");
        if (string.IsNullOrWhiteSpace(path) || !File.Exists(path))
            return;
        if (_session is ContractSessionAdapter adapter)
        {
            await adapter.AttachFileToBlockAsync(CurrentPage().Id, ToContractBlockId(block), path);
            RefreshAfterEdit();
            return;
        }
        block.AttachmentId = "att-local";
        block.AttachmentName = Path.GetFileName(path);
        block.AttachmentSize = new FileInfo(path).Length;
        PushDocumentToBindings();
        _session.MarkDirty();
        RequestRebuild();
    }

    public async Task RemoveAttachmentAsync(string blockId)
    {
        var block = FindBlock(blockId);
        if (block is null)
            return;
        if (_session is ContractSessionAdapter adapter)
        {
            await adapter.DetachAttachmentAsync(CurrentPage().Id, ToContractBlockId(block));
            RefreshAfterEdit();
            return;
        }
        block.AttachmentId = null;
        block.AttachmentName = null;
        block.AttachmentSize = 0;
        PushDocumentToBindings();
        _session.MarkDirty();
        RequestRebuild();
    }

    public async Task OpenAttachmentAsync(string blockId)
    {
        var block = FindBlock(blockId);
        if (block?.AttachmentId is null)
            return;
        if (_session is not ContractSessionAdapter adapter)
        {
            Set("StatusText", $"Attachment: {block.AttachmentName} ({block.AttachmentSize} bytes)");
            return;
        }
        try
        {
            var resolution = await adapter.ResolveAttachmentAsync(block.AttachmentId);
            byte[]? bytes = resolution.EmbeddedBytes;
            if (bytes is null && resolution.SidecarPath is { Length: > 0 } sidecar && File.Exists(sidecar))
                bytes = await File.ReadAllBytesAsync(sidecar);
            if (bytes is null)
            {
                Set("StatusText", "Attachment unavailable: " + FirstLine(resolution.Message));
                return;
            }
            var tempPath = Path.Combine(
                Path.GetTempPath(), "9to1-boards",
                $"{resolution.AttachmentId}-{SanitizeFileName(block.AttachmentName ?? "attachment")}");
            Directory.CreateDirectory(Path.GetDirectoryName(tempPath)!);
            await File.WriteAllBytesAsync(tempPath, bytes);
            try
            {
                System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo(tempPath)
                {
                    UseShellExecute = true,
                });
            }
            catch (Exception launchError)
            {
                Set("StatusText", $"Attachment resolved to {tempPath} (open failed: {FirstLine(launchError.Message)})");
                return;
            }
            Set("StatusText", $"Attachment opened: {tempPath}");
        }
        catch (Exception error)
        {
            Set("StatusText", "Open attachment failed: " + FirstLine(error.Message));
        }
    }

    public void SetDividerStyle(string blockId, string lineStyle)
    {
        var divider = FindBlock(blockId)?.Divider;
        if (divider is null)
            return;
        divider.LineStyle = lineStyle;
        PushDocumentToBindings();
        _session.MarkDirty();
        RequestRebuild();
    }

    public void SetImageAlignment(string blockId, string alignment)
    {
        var image = FindBlock(blockId)?.Image;
        if (image is null)
            return;
        image.Alignment = alignment;
        PushDocumentToBindings();
        _session.MarkDirty();
    }

    public void SetInkTool(string tool)
    {
        InkTool = tool;
        Set("StatusText", $"Ink tool: {tool}");
        RequestRebuild();
    }

    /// <summary>Turns the current note page into its contextual drawing state.</summary>
    public Task ActivateDrawingAsync()
    {
        IsDrawMode = true;
        InkTool = "Pen";
        Set("StatusText", "Draw mode — choose a pen tool and draw on the page");
        RequestRebuild();
        return Task.CompletedTask;
    }

    public void ExitDrawingMode()
    {
        if (!IsDrawMode)
            return;
        IsDrawMode = false;
        Set("StatusText", "Editing notes");
        RequestRebuild();
    }

    public void SetInkColor(string hex)
    {
        InkColor = string.IsNullOrWhiteSpace(hex) ? "#FF111111" : hex.Trim();
        PushDocumentToBindings();
        RequestRebuild();
    }

    public void SetInkWidth(double width)
    {
        InkWidth = Math.Clamp(width, 1, 32);
        PushDocumentToBindings();
        RequestRebuild();
    }

    public async Task SetInkZoomAsync(double zoom)
    {
        InkZoom = Math.Clamp(zoom, 0.25, 8);
        if (_session is ContractSessionAdapter adapter)
            await adapter.SetInkViewAsync(SelectedPageId, InkPanX, InkPanY, InkZoom);
        Set("StatusText", $"Ink zoom: {InkZoom:0.##}x");
    }

    public async Task PanInkViewAsync(double dx, double dy)
    {
        InkPanX += dx;
        InkPanY += dy;
        if (_session is ContractSessionAdapter adapter)
            await adapter.SetInkViewAsync(SelectedPageId, InkPanX, InkPanY, InkZoom);
        Set("StatusText", $"Ink pan: {InkPanX:0}, {InkPanY:0}");
    }

    public async Task ResetInkViewAsync()
    {
        InkZoom = 1;
        InkPanX = 0;
        InkPanY = 0;
        if (_session is ContractSessionAdapter adapter)
            await adapter.SetInkViewAsync(SelectedPageId, 0, 0, 1);
        RequestRebuild();
    }

    public async Task<IReadOnlyList<CanvasBoxView>> GetCanvasObjectsAsync()
    {
        if (_session is ContractSessionAdapter adapter)
        {
            try
            {
                return await adapter.GetCanvasObjectsAsync(SelectedPageId);
            }
            catch (Exception error)
            {
                Set("StatusText", "Freeform unavailable: " + FirstLine(error.Message));
                return [];
            }
        }
        return [];
    }

    public Task<IReadOnlyList<InkStrokeView>> GetInkStrokesAsync(string pageId)
    {
        if (_session is ContractSessionAdapter adapter)
            return adapter.GetInkStrokesAsync(pageId);
        return Task.FromResult<IReadOnlyList<InkStrokeView>>([]);
    }

    public void ReportInkCommitFailure(string message)
        => Set("StatusText", "Ink could not be saved: " + FirstLine(message));

    public bool SupportsFreeform => _session is ContractSessionAdapter;

    public async Task AddCanvasBoxAsync()
    {
        if (_session is not ContractSessionAdapter adapter)
        {
            Set("StatusText", "Freeform canvas needs the contract session");
            return;
        }
        await adapter.AddCanvasObjectAsync(SelectedPageId, "Text", "New note", 40, 40);
        RefreshAfterEdit();
    }

    public async Task MoveCanvasBoxAsync(string objectId, double x, double y)
    {
        if (_session is ContractSessionAdapter adapter)
            await adapter.MoveCanvasObjectAsync(SelectedPageId, objectId, x, y);
        RefreshAfterEdit();
    }

    public async Task RemoveCanvasBoxAsync(string objectId)
    {
        if (_session is ContractSessionAdapter adapter)
            await adapter.RemoveCanvasObjectAsync(SelectedPageId, objectId);
        RefreshAfterEdit();
    }

    // ----- Style catalog CRUD (contract-backed; honest fallback in memory) -----

    public async Task<string?> StyleCreateAsync(string name)
    {
        if (_session is ContractSessionAdapter adapter)
        {
            var id = await adapter.CreateCustomStyleAsync(name);
            RefreshAfterEdit();
            return id;
        }
        Set("StatusText", "Style create needs the contract session");
        return null;
    }

    public async Task StyleRenameAsync(string styleId, string name)
    {
        if (_session is ContractSessionAdapter adapter)
        {
            await adapter.UpdateStyleAsync(styleId, s => s.Name = name);
            RefreshAfterEdit();
            return;
        }
        Set("StatusText", "Style edit needs the contract session");
    }

    public async Task ApplyStyleEditAsync(StyleEditModel model)
    {
        if (_session is not ContractSessionAdapter adapter)
        {
            Set("StatusText", "Style edit needs the contract session");
            return;
        }
        if (string.IsNullOrWhiteSpace(model.Id))
        {
            var created = await adapter.CreateCustomStyleAsync(model.Name);
            await adapter.UpdateStyleAsync(created, s => model.ApplyTo(s));
        }
        else
        {
            await adapter.UpdateStyleAsync(model.Id, s => model.ApplyTo(s));
        }
        RefreshAfterEdit();
    }

    public async Task StyleDeleteAsync(string styleId)
    {
        if (_session is ContractSessionAdapter adapter)
        {
            try
            {
                await adapter.DeleteCustomStyleAsync(styleId);
            }
            catch (Exception error)
            {
                Set("StatusText", "Delete style failed: " + FirstLine(error.Message));
                return;
            }
            RefreshAfterEdit();
            return;
        }
        Set("StatusText", "Style delete needs the contract session");
    }

    public async Task<string?> StyleDuplicateAsync(string styleId)
    {
        if (_session is ContractSessionAdapter adapter)
        {
            var id = await adapter.DuplicateStyleAsync(styleId);
            RefreshAfterEdit();
            return id;
        }
        Set("StatusText", "Style duplicate needs the contract session");
        return null;
    }

    // ----- Internals -----

    private static string FirstLine(string message) =>
        message.Split(['\r', '\n'], StringSplitOptions.RemoveEmptyEntries).FirstOrDefault() ?? message;

    private static string SanitizeFileName(string name)
    {
        foreach (var invalid in Path.GetInvalidFileNameChars())
            name = name.Replace(invalid, '_');
        return string.IsNullOrWhiteSpace(name) ? "attachment" : name;
    }

    private void ToggleBaseline(string baseline)
    {
        var block = SelectedBlock();
        block.Baseline = block.Baseline == baseline ? "normal" : baseline;
        PushDocumentToBindings();
        _session.MarkDirty();
        RequestRebuild();
    }

    private void ClearSelectedFormat()
    {
        var block = SelectedBlock();
        block.Bold = block.Italic = block.Underline = block.Strike = false;
        block.Baseline = "normal";
        block.FontFamily = string.Empty;
        block.FontSize = 0;
        block.Foreground = string.Empty;
        block.Background = string.Empty;
        PushDocumentToBindings();
        _session.MarkDirty();
        RequestRebuild();
    }

    private void ScaleSelectedFont(double delta)
    {
        var block = SelectedBlock();
        var current = block.FontSize > 0 ? block.FontSize : 14;
        block.FontSize = Math.Clamp(current + delta, 8, 96);
        PushDocumentToBindings();
        _session.MarkDirty();
        RequestRebuild();
    }

    public void SetSelectedAlignment(string alignment)
    {
        SelectedBlock().Alignment = alignment;
        PushDocumentToBindings();
        _session.MarkDirty();
        RequestRebuild();
    }

    public void SetSelectedColors(string foreground, string background)
    {
        var block = SelectedBlock();
        block.Foreground = foreground ?? string.Empty;
        block.Background = background ?? string.Empty;
        PushDocumentToBindings();
        _session.MarkDirty();
        RequestRebuild();
    }

    public void SetSelectedFontFamily(string family)
    {
        SelectedBlock().FontFamily = family ?? string.Empty;
        PushDocumentToBindings();
        _session.MarkDirty();
        RequestRebuild();
    }

    public void SetSelectedFontSize(double size)
    {
        SelectedBlock().FontSize = Math.Clamp(size, 8, 96);
        PushDocumentToBindings();
        _session.MarkDirty();
        RequestRebuild();
    }

    public string SelectedBlockKind => SelectedBlockOrNull()?.Kind ?? "paragraph";

    public string SelectedStyleId => SelectedBlockOrNull()?.StyleId ?? "normal";

    public void ShiftSelectedIndent(int delta)
    {
        var block = SelectedBlock();
        block.IndentLevel = Math.Clamp(block.IndentLevel + delta, -1, 8);
        PushDocumentToBindings();
        _session.MarkDirty();
        RequestRebuild();
    }

    private RichBoardBlock ConvertToImageBlock(RichBoardBlock block)
    {
        block.Kind = "image";
        block.Image ??= new RichImageView();
        return block;
    }

    /// <summary>Checklist item ids are "parentId:itemId"; plain ids address the block itself.</summary>
    private RichBoardBlock? FindChecklistBlock(string tail)
    {
        var page = CurrentPage();
        var direct = page.Blocks.FirstOrDefault(b => b.Id == tail);
        if (direct is not null)
            return direct.Kind == "checklist" ? direct : null;
        var cut = tail.LastIndexOf('_');
        if (cut <= 0)
            return null;
        var viewId = tail[..cut] + ":" + tail[(cut + 1)..];
        return page.Blocks.FirstOrDefault(b => b.Id == viewId && b.Kind == "checklist");
    }

    private static (string? ParentId, string ItemId) SplitItemId(string viewBlockId)
    {
        var colon = viewBlockId.IndexOf(':');
        return colon > 0
            ? (viewBlockId[..colon], viewBlockId[(colon + 1)..])
            : (null, viewBlockId);
    }

    private static string ParentKey(string viewBlockId)
    {
        var (parentId, _) = SplitItemId(viewBlockId);
        return parentId ?? viewBlockId;
    }

    private static bool SplitBlockAndTail(string rest, out string blockId, out string tail)
    {
        // Contract block ids never contain '_'; expr ids ("expr-*") neither.
        var cut = rest.LastIndexOf('_');
        if (cut <= 0)
        {
            blockId = string.Empty;
            tail = string.Empty;
            return false;
        }
        blockId = rest[..cut];
        tail = rest[(cut + 1)..];
        return true;
    }

    private static string ToContractBlockId(RichBoardBlock block)
    {
        var (parentId, _) = SplitItemId(block.Id);
        return parentId ?? block.Id;
    }

    private static void EnsureTableDims(RichBoardBlock block)
    {
        if (block.TableRows <= 0)
            block.TableRows = Math.Max(1, block.TableCells.Keys.Select(RowOf).DefaultIfEmpty(0).Max() + 1);
        if (block.TableCols <= 0)
            block.TableCols = Math.Max(1, block.TableCells.Keys.Select(ColOf).DefaultIfEmpty(0).Max() + 1);
    }

    private static int RowOf(string key)
    {
        var cut = key.IndexOf(',');
        return cut > 0 && int.TryParse(key[..cut], out var row) ? row : 0;
    }

    private static int ColOf(string key)
    {
        var cut = key.IndexOf(',');
        return cut >= 0 && int.TryParse(key[(cut + 1)..], out var col) ? col : 0;
    }

    private static string BindingForControl(string controlName) => controlName switch
    {
        "BoardTitleBox" => "BoardTitle",
        "HeadingBox" => "HeadingText",
        "ParaBox" => "ParaText",
        "Check1Box" => "Check1Text",
        "Check1Done" => "Check1Done",
        "Check2Box" => "Check2Text",
        "Check2Done" => "Check2Done",
        "Cell00" => "Cell00",
        "Cell01" => "Cell01",
        "Cell10" => "Cell10",
        "Cell11" => "Cell11",
        _ => controlName,
    };

    private void PushSelectedInfo()
    {
        var selected = CurrentPage().Blocks.FirstOrDefault(b => b.Id == _selectedBlockId)
            ?? CurrentPage().Blocks.FirstOrDefault();
        if (selected is null)
            return;
        Set("SelectedBlockInfo", $"{selected.Kind}: {(selected.Text.Length > 40 ? selected.Text[..40] : selected.Text)}");
        Set("BoldState", selected.Bold ? "On" : "Off");
        Set("ItalicState", selected.Italic ? "On" : "Off");
        Set("UnderlineState", selected.Underline ? "On" : "Off");
    }

    private void PushDocumentToBindings()
    {
        var doc = _session.Document;
        var page = CurrentPage();
        var heading = page.Blocks.FirstOrDefault(b => b.Kind == "heading");
        var para = page.Blocks.FirstOrDefault(b => b.Kind == "paragraph");
        var checks = page.Blocks.Where(b => b.Kind == "checklist").ToList();
        var table = page.Blocks.FirstOrDefault(b => b.Kind == "table");
        var selected = page.Blocks.FirstOrDefault(b => b.Id == _selectedBlockId)
            ?? para ?? heading ?? page.Blocks.FirstOrDefault();

        if (selected is not null)
            _selectedBlockId = selected.Id;

        _syncing = true;
        try
        {
            Set("BoardTitle", doc.Title);
            Set("FilePath", _session.FilePath ?? "memory://boards/default");
            Set("StatusText", _session.Status);
            Set("SectionCount", doc.Sections.Count.ToString());
            Set("PageCount", CurrentSection().Pages.Count.ToString());
            Set("SectionListText", string.Join("  |  ", doc.Sections.Select(s => s.Title)));
            Set("PageListText", string.Join("  |  ", CurrentSection().Pages.Select(p => p.Title)));
            Set("PageTitle", page.Title);
            Set("HeadingText", heading?.Text ?? string.Empty);
            Set("ParaText", para?.Text ?? string.Empty);
            Set("Check1Text", checks.Count > 0 ? checks[0].Text : string.Empty);
            Set("Check1Done", checks.Count > 0 && checks[0].IsChecked);
            Set("Check2Text", checks.Count > 1 ? checks[1].Text : string.Empty);
            Set("Check2Done", checks.Count > 1 && checks[1].IsChecked);
            Set("Cell00", TableCell(table, "0,0"));
            Set("Cell01", TableCell(table, "0,1"));
            Set("Cell10", TableCell(table, "1,0"));
            Set("Cell11", TableCell(table, "1,1"));
            Set("InkSummary", "Drawing is available from the Draw button");
            Set("SelectedBlockInfo", selected is null ? "No block" : $"{selected.Kind}: {(selected.Text.Length > 40 ? selected.Text[..40] : selected.Text)}");
            Set("BoldState", selected?.Bold == true ? "On" : "Off");
            Set("ItalicState", selected?.Italic == true ? "On" : "Off");
            Set("UnderlineState", selected?.Underline == true ? "On" : "Off");
            Set("CanUndo", _session.CanUndo);
            Set("CanRedo", _session.CanRedo);
        }
        finally
        {
            _syncing = false;
        }
    }

    private RichBoardSection CurrentSection() =>
        _session.Document.Sections.FirstOrDefault(s => s.Id == _selectedSectionId)
        ?? _session.Document.Sections.FirstOrDefault()
        ?? throw new InvalidOperationException("Board has no sections.");

    private RichBoardPage CurrentPage()
    {
        var section = CurrentSection();
        return section.Pages.FirstOrDefault(p => p.Id == _selectedPageId)
            ?? section.Pages.FirstOrDefault()
            ?? throw new InvalidOperationException("Section has no pages.");
    }

    private RichBoardBlock SelectedBlock()
    {
        var page = CurrentPage();
        var selected = page.Blocks.FirstOrDefault(b => b.Id == _selectedBlockId)
            ?? page.Blocks.FirstOrDefault();
        if (selected is not null)
            return selected;

        // New notes pages are intentionally empty. Formatting one should begin
        // an editable paragraph rather than throwing on the first toolbar action.
        selected = new RichBoardBlock { Kind = "paragraph" };
        page.Blocks.Add(selected);
        _selectedBlockId = selected.Id;
        return selected;
    }

    private RichBoardBlock FindOrCreateBlock(string kind)
    {
        var page = CurrentPage();
        var block = page.Blocks.FirstOrDefault(b => b.Kind == kind);
        if (block is null)
        {
            block = new RichBoardBlock { Kind = kind };
            page.Blocks.Add(block);
        }
        return block;
    }

    private RichBoardBlock FindChecklist(int index)
    {
        var page = CurrentPage();
        var checks = page.Blocks.Where(b => b.Kind == "checklist").ToList();
        while (checks.Count <= index)
        {
            var added = new RichBoardBlock { Kind = "checklist", Text = $"Item {checks.Count + 1}" };
            page.Blocks.Add(added);
            checks.Add(added);
        }
        return checks[index];
    }

    private void SetTableCell(string key, string value)
    {
        var table = FindOrCreateBlock("table");
        table.TableCells[key] = value;
    }

    private static string TableCell(RichBoardBlock? table, string key) =>
        table is not null && table.TableCells.TryGetValue(key, out var value) ? value : string.Empty;

    private void ReselectDefaults()
    {
        var firstSection = _session.Document.Sections.FirstOrDefault();
        if (firstSection is null)
            return;
        _selectedSectionId = firstSection.Id;
        var page = firstSection.Pages.FirstOrDefault();
        _selectedPageId = page?.Id ?? _selectedPageId;
        if (page is not null)
            SelectExistingBlock(page);
        SyncSelectedInkView();
    }

    private void ReselectAfterUndo()
    {
        var section = _session.Document.Sections.FirstOrDefault(s => s.Id == _selectedSectionId)
            ?? _session.Document.Sections.FirstOrDefault();
        if (section is null)
            return;
        _selectedSectionId = section.Id;
        var page = section.Pages.FirstOrDefault(p => p.Id == _selectedPageId)
            ?? section.Pages.FirstOrDefault();
        if (page is null)
            return;
        _selectedPageId = page.Id;
        SelectExistingBlock(page);
        SyncSelectedInkView();
    }

    private void SelectExistingBlock(RichBoardPage page)
    {
        var selected = page.Blocks.FirstOrDefault(b => b.Id == _selectedBlockId)
            ?? page.Blocks.FirstOrDefault(b => b.Kind == "paragraph")
            ?? page.Blocks.FirstOrDefault();
        _selectedBlockId = selected?.Id ?? string.Empty;
    }

    private void SyncSelectedInkView()
    {
        var page = _session.Document.Sections
            .FirstOrDefault(section => section.Id == _selectedSectionId)?.Pages
            .FirstOrDefault(candidate => candidate.Id == _selectedPageId);
        InkPanX = page?.InkPanX ?? 0;
        InkPanY = page?.InkPanY ?? 0;
        InkZoom = page is null ? 1 : Math.Clamp(page.InkZoom, 0.25, 8);
    }

    private static IEnumerable<T> FindControls<T>(Control root) where T : Control
    {
        if (root is T match)
            yield return match;
        foreach (var child in LogicalChildren(root))
            foreach (var nested in FindControls<T>(child))
                yield return nested;
    }

    private static IEnumerable<Control> LogicalChildren(Control control)
    {
        if (control is Panel panel)
        {
            foreach (var child in panel.Children)
                if (child is Control c)
                    yield return c;
        }
        else if (control is Decorator decorator && decorator.Child is Control decChild)
        {
            yield return decChild;
        }
        else if (control is ContentControl cc)
        {
            if (cc.Content is Control ccChild)
                yield return ccChild;
        }
        else if (control is ItemsControl ic)
        {
            foreach (var item in ic.Items)
                if (item is Control icChild)
                    yield return icChild;
        }
    }
}
