// BoardsViewModel bridges the CUI Boards surface and IRichBoardSession.
// It is both the ICuiBindingContext (all {Binding ...} paths in Boards.cui)
// and the ICuiActionDispatcher (all action="..." commands in Boards.cui).
//
// Editing model: static CUI controls use legacy names (BoardTitleBox,
// HeadingBox, ParaBox, Check1Box...); dynamically rendered blocks use
// id-encoded names (t_{blockId}, done_{parentId}_{itemId},
// chk_{parentId}_{itemId}, cell_{blockId}_{r}_{c}, gx_/gv_/gc_ graph fields,
// gvp_ viewport fields, iw_/ialt_ image fields, dvth_/dvcl_ divider fields).
// Control ids generated by the contract never contain '_', so names are split
// on the LAST '_' (documented in BlockRenderer).

using System.ComponentModel;
using System.Runtime.CompilerServices;
using Avalonia.Controls;
using Avalonia.Input;
using CakeOS.Cui;

namespace CakeOS.Apps.Boards.App;

public sealed class BoardsViewModel : ICuiBindingContext, ICuiActionDispatcher, INotifyPropertyChanged
{
    private readonly IRichBoardSession _session;
    private readonly Dictionary<string, object?> _properties = new(StringComparer.OrdinalIgnoreCase);
    private string _selectedSectionId = "section-1";
    private string _selectedPageId = "page-1";
    private string _selectedBlockId = "block-para";
    private bool _syncing;
    private readonly List<Action> _detachers = [];

    public BoardsViewModel(IRichBoardSession session)
    {
        _session = session ?? throw new ArgumentNullException(nameof(session));
        _session.StatusChanged += (_, status) => Set("StatusText", status);
        PushDocumentToBindings();
        Set("StatusText", _session.Status);
    }

    public IRichBoardSession Session => _session;

    /// <summary>Raised after structural changes so the host can rebuild BlocksHost (never per keystroke).</summary>
    public event Action? RebuildRequested;

    /// <summary>Raised when the style editor dialog should open (host wires the Window).</summary>
    public event Action? StyleEditorRequested;

    /// <summary>Host-provided file picker: kind is "board", "image" or "attach". Null in headless tests.</summary>
    public Func<string, Task<string?>>? PickFileAsync { get; set; }

    /// <summary>Host-provided board switcher used by OpenBoard when set.</summary>
    public Func<Task>? OpenBoardAsync { get; set; }

    public string SelectedBlockId => _selectedBlockId;
    public IReadOnlyList<RichStyleView> StyleList => _session.Styles;
    public IReadOnlyList<RichBoardBlock> PageBlocks => CurrentPage().Blocks;

    public string InkTool { get; set; } = "Pen";
    public double InkWidth { get; set; } = 2.5;
    public string InkColor { get; set; } = "#FF111111";
    public double InkZoom { get; set; } = 1;
    public double InkPanX { get; set; }
    public double InkPanY { get; set; }

    public event PropertyChangedEventHandler? PropertyChanged;

    public void Set(string property, object? value, [CallerMemberName] string? caller = null)
    {
        _properties[property] = value;
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(property));
    }

    public object? Get(string property) =>
        _properties.TryGetValue(property, out var val) ? val : null;

    public bool TryGetValue(string path, out object? value)
    {
        var lastDot = path.LastIndexOf('.');
        var key = lastDot >= 0 ? path[(lastDot + 1)..] : path;
        return _properties.TryGetValue(key, out value);
    }

    public string? StyleName(string styleId) =>
        _session.Styles.FirstOrDefault(s => s.Id == styleId)?.Name ?? styleId;

    public RichBoardBlock? FindBlock(string id) =>
        CurrentPage().Blocks.FirstOrDefault(b => b.Id == id);

    public void RequestRebuild() => RebuildRequested?.Invoke();

    public void RefreshAfterEdit()
    {
        PushDocumentToBindings();
        RequestRebuild();
    }

    public async ValueTask DispatchAsync(string command, object? parameter, CancellationToken cancellationToken = default)
    {
        switch (command)
        {
            case "NewBoard":
                _session.Document.Title = "Untitled board";
                _session.Document.Sections.Clear();
                _session.Document.Sections.Add(InMemoryRichBoardSession.CreateDefault().Sections[0]);
                ReselectDefaults();
                PushDocumentToBindings();
                _session.MarkDirty();
                RequestRebuild();
                break;
            case "OpenBoard":
                await OpenBoardDispatchAsync(cancellationToken);
                break;
            case "SaveBoard":
                await _session.SaveAsync(cancellationToken);
                Set("StatusText", _session.Status);
                RefreshAfterEdit();
                break;
            case "SaveAsBoard":
                var basePath = _session.FilePath ?? "memory://boards/default";
                var copyPath = basePath.EndsWith(".9to1board", StringComparison.OrdinalIgnoreCase)
                    ? basePath[..^".9to1board".Length] + " (copy).9to1board"
                    : basePath + "-copy";
                await _session.SaveAsAsync(copyPath, cancellationToken);
                PushDocumentToBindings();
                RequestRebuild();
                break;
            case "AddBlock":
                CurrentPage().Blocks.Add(new RichBoardBlock { Kind = "paragraph", Text = "New block" });
                PushDocumentToBindings();
                _session.MarkDirty();
                RequestRebuild();
                break;
            case "AddSection":
                var section = new RichBoardSection { Title = $"Section {_session.Document.Sections.Count + 1}" };
                section.Pages.Add(new RichBoardPage { Title = "New page" });
                _session.Document.Sections.Add(section);
                _selectedSectionId = section.Id;
                _selectedPageId = section.Pages[0].Id;
                PushDocumentToBindings();
                _session.MarkDirty();
                RequestRebuild();
                break;
            case "AddPage":
                var page = new RichBoardPage { Title = $"Page {CurrentSection().Pages.Count + 1}" };
                CurrentSection().Pages.Add(page);
                _selectedPageId = page.Id;
                PushDocumentToBindings();
                _session.MarkDirty();
                RequestRebuild();
                break;
            case "ToggleBold":
                SelectedBlock().Bold = !SelectedBlock().Bold;
                PushDocumentToBindings();
                _session.MarkDirty();
                RequestRebuild();
                break;
            case "ToggleItalic":
                SelectedBlock().Italic = !SelectedBlock().Italic;
                PushDocumentToBindings();
                _session.MarkDirty();
                RequestRebuild();
                break;
            case "ToggleUnderline":
                SelectedBlock().Underline = !SelectedBlock().Underline;
                PushDocumentToBindings();
                _session.MarkDirty();
                RequestRebuild();
                break;
            case "ToggleStrike":
                SelectedBlock().Strike = !SelectedBlock().Strike;
                PushDocumentToBindings();
                _session.MarkDirty();
                RequestRebuild();
                break;
            case "ToggleSub":
                ToggleBaseline("subscript");
                break;
            case "ToggleSup":
                ToggleBaseline("superscript");
                break;
            case "ClearFormat":
                ClearSelectedFormat();
                break;
            case "FontBigger":
                ScaleSelectedFont(2);
                break;
            case "FontSmaller":
                ScaleSelectedFont(-2);
                break;
            case "AlignLeft": SetSelectedAlignment("left"); break;
            case "AlignCenter": SetSelectedAlignment("center"); break;
            case "AlignRight": SetSelectedAlignment("right"); break;
            case "AlignJustify": SetSelectedAlignment("justify"); break;
            case "IndentInc": ShiftSelectedIndent(1); break;
            case "IndentDec": ShiftSelectedIndent(-1); break;
            case "Undo":
                if (await _session.UndoAsync(cancellationToken))
                    Set("StatusText", _session.Status);
                else
                    Set("StatusText", "Nothing to undo");
                ReselectAfterUndo();
                RefreshAfterEdit();
                break;
            case "Redo":
                if (await _session.RedoAsync(cancellationToken))
                    Set("StatusText", _session.Status);
                else
                    Set("StatusText", "Nothing to redo");
                ReselectAfterUndo();
                RefreshAfterEdit();
                break;
            case "ManageStyles":
                StyleEditorRequested?.Invoke();
                break;
            case "AddInkDot":
                AddInkStroke();
                break;
            case "ClearInk":
                await ClearInkAsync(cancellationToken);
                break;
            case "SelectSection1":
                if (_session.Document.Sections.Count > 0)
                {
                    _selectedSectionId = _session.Document.Sections[0].Id;
                    _selectedPageId = CurrentSection().Pages.Count > 0 ? CurrentSection().Pages[0].Id : _selectedPageId;
                    PushDocumentToBindings();
                    RequestRebuild();
                }
                break;
            case "SelectSection2":
                if (_session.Document.Sections.Count > 1)
                {
                    _selectedSectionId = _session.Document.Sections[1].Id;
                    _selectedPageId = CurrentSection().Pages.Count > 0 ? CurrentSection().Pages[0].Id : _selectedPageId;
                    PushDocumentToBindings();
                    RequestRebuild();
                }
                break;
            case "SelectPage1":
                if (CurrentSection().Pages.Count > 0)
                {
                    _selectedPageId = CurrentSection().Pages[0].Id;
                    PushDocumentToBindings();
                    RequestRebuild();
                }
                break;
            case "SelectPage2":
                if (CurrentSection().Pages.Count > 1)
                {
                    _selectedPageId = CurrentSection().Pages[1].Id;
                    PushDocumentToBindings();
                    RequestRebuild();
                }
                break;
        }
    }

    private async Task OpenBoardDispatchAsync(CancellationToken cancellationToken)
    {
        if (OpenBoardAsync is not null)
        {
            await OpenBoardAsync();
            return;
        }
        var picked = PickFileAsync is not null ? await PickFileAsync("board") : null;
        try
        {
            await _session.OpenAsync(picked ?? _session.FilePath, cancellationToken);
            ReselectDefaults();
            PushDocumentToBindings();
            RequestRebuild();
        }
        catch (Exception error)
        {
            Set("StatusText", "Open failed: " + FirstLine(error.Message));
        }
    }

    /// <summary>
    /// Wire live editing: subscribes to named TextBox/CheckBox controls built
    /// by CuiControlLoader so multiline edits update session state (dirty +
    /// debounced autosave). The loader itself only pushes one-way bindings.
    /// Dynamically rendered BlocksHost children wire their own handlers in
    /// BlockRenderer; this covers the static CUI surface.
    /// </summary>
    public void Attach(Control root)
    {
        foreach (var textBox in FindControls<TextBox>(root))
        {
            var name = textBox.Name ?? string.Empty;
            EventHandler<TextChangedEventArgs> textHandler = (_, _) =>
            {
                if (_syncing)
                    return;
                EditText(name, textBox.Text ?? string.Empty);
            };
            EventHandler<FocusChangedEventArgs> focusHandler = (_, _) =>
            {
                if (_syncing)
                    return;
                FocusBlockFromControl(name);
            };
            textBox.TextChanged += textHandler;
            textBox.GotFocus += focusHandler;
            _detachers.Add(() =>
            {
                textBox.TextChanged -= textHandler;
                textBox.GotFocus -= focusHandler;
            });
        }
        foreach (var checkBox in FindControls<CheckBox>(root))
        {
            var name = checkBox.Name ?? string.Empty;
            EventHandler<Avalonia.Interactivity.RoutedEventArgs> checkHandler = (_, _) =>
            {
                if (_syncing)
                    return;
                EditCheck(name, checkBox.IsChecked == true);
            };
            checkBox.IsCheckedChanged += checkHandler;
            _detachers.Add(() => checkBox.IsCheckedChanged -= checkHandler);
        }
        SyncControlValues(root);
    }

    /// <summary>Unsubscribe all Attach handlers (used when switching boards).</summary>
    public void Detach()
    {
        foreach (var remove in _detachers)
        {
            try { remove(); }
            catch { /* Detach is best-effort. */ }
        }
        _detachers.Clear();
    }

    /// <summary>Push current binding values into live controls without re-firing edits.</summary>
    public void SyncControlValues(Control root)
    {
        _syncing = true;
        try
        {
            foreach (var textBox in FindControls<TextBox>(root))
            {
                var value = Get(BindingForControl(textBox.Name ?? string.Empty))?.ToString();
                if (value is not null && textBox.Text != value)
                    textBox.Text = value;
            }
            foreach (var checkBox in FindControls<CheckBox>(root))
            {
                var value = Get(BindingForControl(checkBox.Name ?? string.Empty))?.ToString();
                if (value is not null && bool.TryParse(value, out var done) && checkBox.IsChecked != done)
                    checkBox.IsChecked = done;
            }
        }
        finally
        {
            _syncing = false;
        }
    }

    public void AddInkStroke(double x = 60, double y = 40)
    {
        if (_session is ContractSessionAdapter adapter)
        {
            _ = CommitSampleInkAsync(adapter);
            return;
        }
        var ink = CurrentPage().Blocks.FirstOrDefault(b => b.Kind == "ink");
        if (ink is null)
        {
            ink = new RichBoardBlock { Kind = "ink", Text = "Sketch" };
            CurrentPage().Blocks.Add(ink);
        }
        ink.InkStrokeCount++;
        PushDocumentToBindings();
        _session.MarkDirty();
        RequestRebuild();
    }

    /// <summary>Commits one pointer-drawn stroke as real persisted ink data.</summary>
    public async ValueTask CommitInkStrokeAsync(IReadOnlyList<(double X, double Y)> points)
    {
        if (_session is ContractSessionAdapter adapter)
        {
            await adapter.CommitInkStrokeAsync(points);
            PushDocumentToBindings();
            RequestRebuild();
            return;
        }
        AddInkStroke();
    }

    /// <summary>Commits one pressure-aware stroke with the selected tool/width/color.</summary>
    public async ValueTask CommitInkStrokeAsync(
        IReadOnlyList<(double X, double Y, double Pressure)> points,
        double width, string color, string tool)
    {
        if (_session is ContractSessionAdapter adapter)
        {
            await adapter.CommitInkStrokeAsync(points, width, color, tool);
            PushDocumentToBindings();
            RequestRebuild();
            return;
        }
        AddInkStroke();
    }

    public async ValueTask ClearInkAsync(CancellationToken cancellationToken = default)
    {
        if (_session is ContractSessionAdapter adapter)
        {
            await adapter.ClearInkAsync(cancellationToken);
            PushDocumentToBindings();
            RequestRebuild();
            Set("StatusText", _session.Status);
            return;
        }
        var ink = CurrentPage().Blocks.FirstOrDefault(b => b.Kind == "ink");
        if (ink is not null)
            ink.InkStrokeCount = 0;
        PushDocumentToBindings();
        _session.MarkDirty();
        RequestRebuild();
    }

    private async Task CommitSampleInkAsync(ContractSessionAdapter adapter)
    {
        await adapter.AddSampleInkStrokeAsync();
        PushDocumentToBindings();
        RequestRebuild();
    }

    // ----- Generalized id-encoded editing (legacy names keep working) -----

    public void EditText(string controlName, string text)
    {
        switch (controlName)
        {
            case "BoardTitleBox":
                _session.Document.Title = text;
                Set("BoardTitle", text);
                break;
            case "HeadingBox":
                FindOrCreateBlock("heading").Text = text;
                Set("HeadingText", text);
                break;
            case "ParaBox":
                FindOrCreateBlock("paragraph").Text = text;
                Set("ParaText", text);
                _selectedBlockId = FindOrCreateBlock("paragraph").Id;
                break;
            case "Check1Box":
                FindChecklist(0).Text = text;
                Set("Check1Text", text);
                break;
            case "Check2Box":
                FindChecklist(1).Text = text;
                Set("Check2Text", text);
                break;
            case "Cell00": SetTableCell("0,0", text); Set("Cell00", text); break;
            case "Cell01": SetTableCell("0,1", text); Set("Cell01", text); break;
            case "Cell10": SetTableCell("1,0", text); Set("Cell10", text); break;
            case "Cell11": SetTableCell("1,1", text); Set("Cell11", text); break;
            default:
                if (!EditDynamicText(controlName, text))
                    return;
                break;
        }
        _session.MarkDirty();
    }

    private bool EditDynamicText(string controlName, string text)
    {
        // t_{blockId}: paragraph/heading body.
        if (controlName.StartsWith("t_", StringComparison.Ordinal))
        {
            var block = FindBlock(controlName["t_".Length..]);
            if (block is null)
                return false;
            block.Text = text;
            _selectedBlockId = block.Id;
            PushSelectedInfo();
            return true;
        }
        // chk_{parentId}_{itemId} or chk_{plainId}: checklist item text.
        if (controlName.StartsWith("chk_", StringComparison.Ordinal))
        {
            var block = FindChecklistBlock(controlName["chk_".Length..]);
            if (block is null)
                return false;
            block.Text = text;
            _selectedBlockId = block.Id;
            return true;
        }
        // cell_{blockId}_{r}_{c}: table cell text.
        if (controlName.StartsWith("cell_", StringComparison.Ordinal))
        {
            var rest = controlName["cell_".Length..].Split('_');
            if (rest.Length < 3 || !int.TryParse(rest[^2], out var row) || !int.TryParse(rest[^1], out var col))
                return false;
            var blockId = string.Join("_", rest[..^2]);
            var block = FindBlock(blockId);
            if (block is null || block.Kind != "table")
                return false;
            block.TableCells[$"{row},{col}"] = text;
            _selectedBlockId = block.Id;
            return true;
        }
        // gx_{blockId}_{exprId}: graph expression text.
        if (controlName.StartsWith("gx_", StringComparison.Ordinal))
        {
            if (!SplitBlockAndTail(controlName["gx_".Length..], out var blockId, out var exprId))
                return false;
            var expr = FindBlock(blockId)?.Graph?.Expressions.FirstOrDefault(e => e.Id == exprId);
            if (expr is null)
                return false;
            expr.Text = text;
            _selectedBlockId = blockId;
            return true;
        }
        // gc_{blockId}_{exprId}: graph expression color.
        if (controlName.StartsWith("gc_", StringComparison.Ordinal))
        {
            if (!SplitBlockAndTail(controlName["gc_".Length..], out var blockId, out var exprId))
                return false;
            var expr = FindBlock(blockId)?.Graph?.Expressions.FirstOrDefault(e => e.Id == exprId);
            if (expr is null)
                return false;
            expr.Color = text;
            return true;
        }
        // gvp_{field}_{blockId}: graph viewport doubles.
        if (controlName.StartsWith("gvp_", StringComparison.Ordinal))
            return EditViewportField(controlName["gvp_".Length..], text);
        // iw_{blockId} / ialt_{blockId}: image width / alt text.
        if (controlName.StartsWith("iw_", StringComparison.Ordinal))
        {
            var block = FindBlock(controlName["iw_".Length..]);
            if (block?.Image is null)
                return false;
            if (double.TryParse(text, out var width) && width is >= 0 and <= 8000)
                block.Image.Width = width;
            return true;
        }
        if (controlName.StartsWith("ialt_", StringComparison.Ordinal))
        {
            var block = FindBlock(controlName["ialt_".Length..]);
            if (block?.Image is null)
                return false;
            block.Image.AltText = text;
            return true;
        }
        // dvth_{blockId} / dvcl_{blockId}: divider thickness / color.
        if (controlName.StartsWith("dvth_", StringComparison.Ordinal))
        {
            var block = FindBlock(controlName["dvth_".Length..]);
            if (block?.Divider is null)
                return false;
            if (double.TryParse(text, out var thickness) && thickness is > 0 and <= 64)
                block.Divider.Thickness = thickness;
            return true;
        }
        if (controlName.StartsWith("dvcl_", StringComparison.Ordinal))
        {
            var block = FindBlock(controlName["dvcl_".Length..]);
            if (block?.Divider is null)
                return false;
            block.Divider.Color = text;
            return true;
        }
        // inkwidth / inkcolor: session-level ink defaults (static names).
        if (controlName == "InkWidthBox")
        {
            if (double.TryParse(text, out var width) && width is > 0 and <= 64)
                InkWidth = width;
            return true;
        }
        if (controlName == "InkColorBox")
        {
            if (!string.IsNullOrWhiteSpace(text))
                InkColor = text.Trim();
            return true;
        }
        return false;
    }

    private bool EditViewportField(string rest, string text)
    {
        // rest = {field}_{blockId}; block ids never contain '_' from the contract.
        var cut = rest.LastIndexOf('_');
        if (cut <= 0)
            return false;
        var field = rest[..cut];
        var blockId = rest[(cut + 1)..];
        var graph = FindBlock(blockId)?.Graph;
        if (graph is null || !double.TryParse(text, out var value) || !double.IsFinite(value))
            return false;
        switch (field.ToLowerInvariant())
        {
            case "xmin": graph.XMin = value; break;
            case "xmax": graph.XMax = value; break;
            case "ymin": graph.YMin = value; break;
            case "ymax": graph.YMax = value; break;
            default: return false;
        }
        _selectedBlockId = blockId;
        return true;
    }

    public void EditCheck(string controlName, bool done)
    {
        switch (controlName)
        {
            case "Check1Done": FindChecklist(0).IsChecked = done; Set("Check1Done", done); break;
            case "Check2Done": FindChecklist(1).IsChecked = done; Set("Check2Done", done); break;
            default:
                if (!EditDynamicCheck(controlName, done))
                    return;
                break;
        }
        _session.MarkDirty();
    }

    private bool EditDynamicCheck(string controlName, bool done)
    {
        // done_{parentId}_{itemId} or done_{plainId}.
        if (controlName.StartsWith("done_", StringComparison.Ordinal))
        {
            var block = FindChecklistBlock(controlName["done_".Length..]);
            if (block is null)
                return false;
            block.IsChecked = done;
            _selectedBlockId = block.Id;
            return true;
        }
        // gv_{blockId}_{exprId}: graph expression visibility.
        if (controlName.StartsWith("gv_", StringComparison.Ordinal))
        {
            if (!SplitBlockAndTail(controlName["gv_".Length..], out var blockId, out var exprId))
                return false;
            var expr = FindBlock(blockId)?.Graph?.Expressions.FirstOrDefault(e => e.Id == exprId);
            if (expr is null)
                return false;
            expr.Visible = done;
            _selectedBlockId = blockId;
            return true;
        }
        return false;
    }

    public void FocusBlock(string blockId)
    {
        if (FindBlock(blockId) is null)
            return;
        _selectedBlockId = blockId;
        PushSelectedInfo();
    }

    private void FocusBlockFromControl(string controlName)
    {
        var legacy = controlName switch
        {
            "HeadingBox" => FindOrCreateBlock("heading").Id,
            "ParaBox" => FindOrCreateBlock("paragraph").Id,
            "Check1Box" or "Check1Done" => FindChecklist(0).Id,
            "Check2Box" or "Check2Done" => FindChecklist(1).Id,
            "Cell00" or "Cell01" or "Cell10" or "Cell11" => FindOrCreateBlock("table").Id,
            _ => null,
        };
        if (legacy is not null)
        {
            FocusBlock(legacy);
            return;
        }
        if (controlName.StartsWith("t_", StringComparison.Ordinal))
            FocusBlock(controlName["t_".Length..]);
        else if (controlName.StartsWith("chk_", StringComparison.Ordinal)
            || controlName.StartsWith("done_", StringComparison.Ordinal))
        {
            var tail = controlName[(controlName.IndexOf('_') + 1)..];
            var block = FindChecklistBlock(tail);
            if (block is not null)
                FocusBlock(block.Id);
        }
        else if (controlName.StartsWith("cell_", StringComparison.Ordinal))
        {
            var rest = controlName["cell_".Length..].Split('_');
            if (rest.Length >= 3)
                FocusBlock(string.Join("_", rest[..^2]));
        }
    }

    // ----- Block operations used by BlockRenderer -----

    public async Task InsertKindAsync(string kindTag)
    {
        if (kindTag.StartsWith("style:", StringComparison.Ordinal))
        {
            await ApplyStyleToSelectedAsync(kindTag["style:".Length..]);
            return;
        }
        var page = CurrentPage();
        RichBoardBlock block = kindTag switch
        {
            "heading" => new RichBoardBlock { Kind = "heading", Text = "New heading" },
            "checklist" => new RichBoardBlock { Kind = "checklist", Text = "New item" },
            "table" => new RichBoardBlock
            {
                Kind = "table", Text = "New table", TableRows = 2, TableCols = 2,
                TableCells = new Dictionary<string, string>(StringComparer.Ordinal)
                {
                    ["0,0"] = string.Empty, ["0,1"] = string.Empty,
                    ["1,0"] = string.Empty, ["1,1"] = string.Empty,
                },
            },
            "image" => new RichBoardBlock
            {
                Kind = "image", Text = "image",
                Image = new RichImageView { DisplayName = "image (choose a file)", MediaType = "image/png" },
            },
            "divider" => new RichBoardBlock
            {
                Kind = "divider",
                Divider = new RichDividerView { Thickness = 1, LineStyle = "solid", Color = "#FF5F6368" },
            },
            "graph" => new RichBoardBlock
            {
                Kind = "graph",
                Graph = new RichGraphView
                {
                    Expressions = [new RichGraphExpressionView { Text = "y = x" }],
                    XMin = -10, XMax = 10, YMin = -10, YMax = 10,
                },
            },
            _ => new RichBoardBlock { Kind = "paragraph", Text = "New block" },
        };
        page.Blocks.Add(block);
        _selectedBlockId = block.Id;
        PushDocumentToBindings();
        _session.MarkDirty();
        if (kindTag == "image")
            Set("StatusText", "Image block added — use Replace to choose a file");
        RequestRebuild();
        if (kindTag == "image")
            await ReplaceImageAsync(block.Id);
    }

    public async Task ApplyStyleToSelectedAsync(string styleId)
    {
        if (string.IsNullOrWhiteSpace(styleId))
            return;
        if (!_session.Styles.Any(s => s.Id == styleId))
        {
            Set("StatusText", $"Style '{styleId}' was not found");
            return;
        }
        SelectedBlock().StyleId = styleId;
        PushDocumentToBindings();
        _session.MarkDirty();
        RequestRebuild();
    }

    public async Task DeleteBlockAsync(string viewBlockId)
    {
        if (_session is ContractSessionAdapter adapter)
        {
            await adapter.DeleteViewBlockAsync(CurrentPage().Id, viewBlockId);
            ReselectAfterUndo();
            RefreshAfterEdit();
            return;
        }
        var page = CurrentPage();
        var removed = page.Blocks.RemoveAll(b => b.Id == viewBlockId);
        if (removed == 0)
        {
            Set("StatusText", "Block was not found");
            return;
        }
        ReselectAfterUndo();
        PushDocumentToBindings();
        _session.MarkDirty();
        RequestRebuild();
    }

    public async Task AddChecklistItemAsync(string parentViewBlockId, string text = "New item")
    {
        var (parentId, _) = SplitItemId(parentViewBlockId);
        if (_session is ContractSessionAdapter adapter && parentId is not null)
        {
            // Targeted parent insert through the adapter (merge would use the first list).
            await adapter.AddChecklistItemAsync(CurrentPage().Id, parentId, text);
            RefreshAfterEdit();
            return;
        }
        CurrentPage().Blocks.Add(new RichBoardBlock { Kind = "checklist", Text = text });
        PushDocumentToBindings();
        _session.MarkDirty();
        RequestRebuild();
    }

    /// <summary>Enter at the end of a checklist row appends the next item.</summary>
    public async Task ChecklistEnterAsync(string viewBlockId)
    {
        var block = FindChecklistBlock(viewBlockId);
        var parentKey = block is not null ? ParentKey(block.Id) : viewBlockId;
        await AddChecklistItemAsync(parentKey);
    }

    /// <summary>Backspace on an empty checklist row removes it.</summary>
    public async Task ChecklistBackspaceAsync(string viewBlockId, string currentText)
    {
        if (!string.IsNullOrEmpty(currentText))
            return;
        var block = FindChecklistBlock(viewBlockId);
        if (block is null)
            return;
        // Never delete the final checklist row; clear it instead.
        if (CurrentPage().Blocks.Count(b => b.Kind == "checklist") <= 1)
        {
            block.Text = string.Empty;
            PushDocumentToBindings();
            _session.MarkDirty();
            RequestRebuild();
            return;
        }
        await DeleteBlockAsync(block.Id);
    }

    public void ChecklistIndent(string viewBlockId, int delta)
    {
        var block = FindChecklistBlock(viewBlockId);
        if (block is null)
            return;
        block.Level = Math.Clamp(block.Level + delta, 0, 8);
        PushDocumentToBindings();
        _session.MarkDirty();
    }

    public void TableAddRow(string blockId)
    {
        var block = FindBlock(blockId);
        if (block is null || block.Kind != "table")
            return;
        EnsureTableDims(block);
        block.TableRows = Math.Min(100, block.TableRows + 1);
        PushDocumentToBindings();
        _session.MarkDirty();
        RequestRebuild();
    }

    public void TableDelRow(string blockId)
    {
        var block = FindBlock(blockId);
        if (block is null || block.Kind != "table")
            return;
        EnsureTableDims(block);
        if (block.TableRows <= 1)
            return;
        block.TableRows--;
        var doomed = block.TableCells.Keys.Where(k => RowOf(k) >= block.TableRows).ToArray();
        foreach (var key in doomed)
            block.TableCells.Remove(key);
        var doomedStyles = block.CellStyles.Keys.Where(k => RowOf(k) >= block.TableRows).ToArray();
        foreach (var key in doomedStyles)
            block.CellStyles.Remove(key);
        PushDocumentToBindings();
        _session.MarkDirty();
        RequestRebuild();
    }

    public void TableAddCol(string blockId)
    {
        var block = FindBlock(blockId);
        if (block is null || block.Kind != "table")
            return;
        EnsureTableDims(block);
        block.TableCols = Math.Min(50, block.TableCols + 1);
        PushDocumentToBindings();
        _session.MarkDirty();
        RequestRebuild();
    }

    public void TableDelCol(string blockId)
    {
        var block = FindBlock(blockId);
        if (block is null || block.Kind != "table")
            return;
        EnsureTableDims(block);
        if (block.TableCols <= 1)
            return;
        block.TableCols--;
        var doomed = block.TableCells.Keys.Where(k => ColOf(k) >= block.TableCols).ToArray();
        foreach (var key in doomed)
            block.TableCells.Remove(key);
        var doomedStyles = block.CellStyles.Keys.Where(k => ColOf(k) >= block.TableCols).ToArray();
        foreach (var key in doomedStyles)
            block.CellStyles.Remove(key);
        PushDocumentToBindings();
        _session.MarkDirty();
        RequestRebuild();
    }

    public void SetCellAlign(string blockId, int row, int col, string alignH)
    {
        var block = FindBlock(blockId);
        if (block is null || block.Kind != "table")
            return;
        var style = block.CellStyles.TryGetValue($"{row},{col}", out var existing)
            ? existing
            : block.CellStyles[$"{row},{col}"] = new RichCellStyleView();
        style.AlignH = alignH;
        _session.MarkDirty();
    }

    public void ToggleCellBold(string blockId, int row, int col)
    {
        var block = FindBlock(blockId);
        if (block is null || block.Kind != "table")
            return;
        var style = block.CellStyles.TryGetValue($"{row},{col}", out var existing)
            ? existing
            : block.CellStyles[$"{row},{col}"] = new RichCellStyleView();
        style.Bold = !style.Bold;
        PushDocumentToBindings();
        _session.MarkDirty();
        RequestRebuild();
    }

    public void GraphAddExpression(string blockId, string text = "y = x")
    {
        var graph = FindBlock(blockId)?.Graph;
        if (graph is null || graph.Expressions.Count >= 32)
            return;
        graph.Expressions.Add(new RichGraphExpressionView { Text = text });
        PushDocumentToBindings();
        _session.MarkDirty();
        RequestRebuild();
    }

    public async Task GraphDeleteExpressionAsync(string blockId, string exprId)
    {
        var graph = FindBlock(blockId)?.Graph;
        if (graph is null)
            return;
        graph.Expressions.RemoveAll(e => e.Id == exprId);
        if (graph.Expressions.Count == 0)
            graph.Expressions.Add(new RichGraphExpressionView { Text = "y = x" });
        PushDocumentToBindings();
        _session.MarkDirty();
        RequestRebuild();
        await Task.CompletedTask;
    }

    public void GraphPanZoom(string blockId, double dx, double dy, double factor)
    {
        var graph = FindBlock(blockId)?.Graph;
        if (graph is null)
            return;
        var width = graph.XMax - graph.XMin;
        var height = graph.YMax - graph.YMin;
        if (factor != 1)
        {
            width /= factor;
            height /= factor;
            var cx = (graph.XMin + graph.XMax) / 2;
            var cy = (graph.YMin + graph.YMax) / 2;
            graph.XMin = cx - width / 2;
            graph.XMax = cx + width / 2;
            graph.YMin = cy - height / 2;
            graph.YMax = cy + height / 2;
        }
        if (dx != 0 || dy != 0)
        {
            graph.XMin += dx * width;
            graph.XMax += dx * width;
            graph.YMin += dy * height;
            graph.YMax += dy * height;
        }
        PushDocumentToBindings();
        _session.MarkDirty();
        RequestRebuild();
    }

    public async Task ReplaceImageAsync(string blockId)
    {
        var block = FindBlock(blockId);
        if (block is null || (block.Kind != "image" && block.Kind != "paragraph" && block.Kind != "heading"))
            return;
        if (PickFileAsync is null)
        {
            Set("StatusText", "Image pick needs the desktop host");
            return;
        }
        var path = await PickFileAsync("image");
        if (string.IsNullOrWhiteSpace(path) || !File.Exists(path))
            return;
        var bytes = await File.ReadAllBytesAsync(path);
        var mediaType = Path.GetExtension(path).ToLowerInvariant() switch
        {
            ".jpg" or ".jpeg" => "image/jpeg",
            ".gif" => "image/gif",
            ".bmp" => "image/bmp",
            ".webp" => "image/webp",
            _ => "image/png",
        };
        var target = block.Kind == "image" ? block : ConvertToImageBlock(block);
        target.Image = new RichImageView
        {
            DisplayName = Path.GetFileName(path),
            MediaType = mediaType,
            DataBase64 = Convert.ToBase64String(bytes),
            Width = target.Image?.Width ?? 0,
            Alignment = target.Image?.Alignment ?? "inherit",
            AltText = target.Image?.AltText ?? string.Empty,
        };
        target.Text = target.Image.DisplayName;
        PushDocumentToBindings();
        _session.MarkDirty();
        RequestRebuild();
    }

    public async Task AttachFileAsync(string blockId)
    {
        var block = FindBlock(blockId);
        if (block is null)
            return;
        if (PickFileAsync is null)
        {
            Set("StatusText", "Attachment pick needs the desktop host");
            return;
        }
        var path = await PickFileAsync("attach");
        if (string.IsNullOrWhiteSpace(path) || !File.Exists(path))
            return;
        if (_session is ContractSessionAdapter adapter)
        {
            await adapter.AttachFileToBlockAsync(CurrentPage().Id, ToContractBlockId(block), path);
            RefreshAfterEdit();
            return;
        }
        block.AttachmentId = "att-local";
        block.AttachmentName = Path.GetFileName(path);
        block.AttachmentSize = new FileInfo(path).Length;
        PushDocumentToBindings();
        _session.MarkDirty();
        RequestRebuild();
    }

    public async Task RemoveAttachmentAsync(string blockId)
    {
        var block = FindBlock(blockId);
        if (block is null)
            return;
        if (_session is ContractSessionAdapter adapter)
        {
            await adapter.DetachAttachmentAsync(CurrentPage().Id, ToContractBlockId(block));
            RefreshAfterEdit();
            return;
        }
        block.AttachmentId = null;
        block.AttachmentName = null;
        block.AttachmentSize = 0;
        PushDocumentToBindings();
        _session.MarkDirty();
        RequestRebuild();
    }

    public async Task OpenAttachmentAsync(string blockId)
    {
        var block = FindBlock(blockId);
        if (block?.AttachmentId is null)
            return;
        if (_session is not ContractSessionAdapter adapter)
        {
            Set("StatusText", $"Attachment: {block.AttachmentName} ({block.AttachmentSize} bytes)");
            return;
        }
        try
        {
            var resolution = await adapter.ResolveAttachmentAsync(block.AttachmentId);
            byte[]? bytes = resolution.EmbeddedBytes;
            if (bytes is null && resolution.SidecarPath is { Length: > 0 } sidecar && File.Exists(sidecar))
                bytes = await File.ReadAllBytesAsync(sidecar);
            if (bytes is null)
            {
                Set("StatusText", "Attachment unavailable: " + FirstLine(resolution.Message));
                return;
            }
            var tempPath = Path.Combine(
                Path.GetTempPath(), "9to1-boards",
                $"{resolution.AttachmentId}-{SanitizeFileName(block.AttachmentName ?? "attachment")}");
            Directory.CreateDirectory(Path.GetDirectoryName(tempPath)!);
            await File.WriteAllBytesAsync(tempPath, bytes);
            try
            {
                System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo(tempPath)
                {
                    UseShellExecute = true,
                });
            }
            catch (Exception launchError)
            {
                Set("StatusText", $"Attachment resolved to {tempPath} (open failed: {FirstLine(launchError.Message)})");
                return;
            }
            Set("StatusText", $"Attachment opened: {tempPath}");
        }
        catch (Exception error)
        {
            Set("StatusText", "Open attachment failed: " + FirstLine(error.Message));
        }
    }

    public void SetDividerStyle(string blockId, string lineStyle)
    {
        var divider = FindBlock(blockId)?.Divider;
        if (divider is null)
            return;
        divider.LineStyle = lineStyle;
        PushDocumentToBindings();
        _session.MarkDirty();
        RequestRebuild();
    }

    public void SetImageAlignment(string blockId, string alignment)
    {
        var image = FindBlock(blockId)?.Image;
        if (image is null)
            return;
        image.Alignment = alignment;
        PushDocumentToBindings();
        _session.MarkDirty();
    }

    public void SetInkTool(string tool)
    {
        InkTool = tool;
        Set("StatusText", $"Ink tool: {tool}");
    }

    public async Task SetInkZoomAsync(double zoom)
    {
        InkZoom = Math.Clamp(zoom, 0.25, 8);
        if (_session is ContractSessionAdapter adapter)
            await adapter.SetInkViewAsync(InkPanX, InkPanY, InkZoom);
        Set("StatusText", $"Ink zoom: {InkZoom:0.##}x");
    }

    public async Task ResetInkViewAsync()
    {
        InkZoom = 1;
        InkPanX = 0;
        InkPanY = 0;
        if (_session is ContractSessionAdapter adapter)
            await adapter.SetInkViewAsync(0, 0, 1);
        RequestRebuild();
    }

    public async Task<IReadOnlyList<CanvasBoxView>> GetCanvasObjectsAsync()
    {
        if (_session is ContractSessionAdapter adapter)
        {
            try
            {
                return await adapter.GetCanvasObjectsAsync();
            }
            catch (Exception error)
            {
                Set("StatusText", "Freeform unavailable: " + FirstLine(error.Message));
                return [];
            }
        }
        return [];
    }

    public bool SupportsFreeform => _session is ContractSessionAdapter;

    public async Task AddCanvasBoxAsync()
    {
        if (_session is not ContractSessionAdapter adapter)
        {
            Set("StatusText", "Freeform canvas needs the contract session");
            return;
        }
        await adapter.AddCanvasObjectAsync("Text", "New note", 40, 40);
        RefreshAfterEdit();
    }

    public async Task MoveCanvasBoxAsync(string objectId, double x, double y)
    {
        if (_session is ContractSessionAdapter adapter)
            await adapter.MoveCanvasObjectAsync(objectId, x, y);
        RefreshAfterEdit();
    }

    public async Task RemoveCanvasBoxAsync(string objectId)
    {
        if (_session is ContractSessionAdapter adapter)
            await adapter.RemoveCanvasObjectAsync(objectId);
        RefreshAfterEdit();
    }

    // ----- Style catalog CRUD (contract-backed; honest fallback in memory) -----

    public async Task<string?> StyleCreateAsync(string name)
    {
        if (_session is ContractSessionAdapter adapter)
        {
            var id = await adapter.CreateCustomStyleAsync(name);
            RefreshAfterEdit();
            return id;
        }
        Set("StatusText", "Style create needs the contract session");
        return null;
    }

    public async Task StyleRenameAsync(string styleId, string name)
    {
        if (_session is ContractSessionAdapter adapter)
        {
            await adapter.UpdateStyleAsync(styleId, s => s.Name = name);
            RefreshAfterEdit();
            return;
        }
        Set("StatusText", "Style edit needs the contract session");
    }

    public async Task ApplyStyleEditAsync(StyleEditModel model)
    {
        if (_session is not ContractSessionAdapter adapter)
        {
            Set("StatusText", "Style edit needs the contract session");
            return;
        }
        if (string.IsNullOrWhiteSpace(model.Id))
        {
            var created = await adapter.CreateCustomStyleAsync(model.Name);
            await adapter.UpdateStyleAsync(created, s => model.ApplyTo(s));
        }
        else
        {
            await adapter.UpdateStyleAsync(model.Id, s => model.ApplyTo(s));
        }
        RefreshAfterEdit();
    }

    public async Task StyleDeleteAsync(string styleId)
    {
        if (_session is ContractSessionAdapter adapter)
        {
            try
            {
                await adapter.DeleteCustomStyleAsync(styleId);
            }
            catch (Exception error)
            {
                Set("StatusText", "Delete style failed: " + FirstLine(error.Message));
                return;
            }
            RefreshAfterEdit();
            return;
        }
        Set("StatusText", "Style delete needs the contract session");
    }

    public async Task<string?> StyleDuplicateAsync(string styleId)
    {
        if (_session is ContractSessionAdapter adapter)
        {
            var id = await adapter.DuplicateStyleAsync(styleId);
            RefreshAfterEdit();
            return id;
        }
        Set("StatusText", "Style duplicate needs the contract session");
        return null;
    }

    // ----- Internals -----

    private static string FirstLine(string message) =>
        message.Split(['\r', '\n'], StringSplitOptions.RemoveEmptyEntries).FirstOrDefault() ?? message;

    private static string SanitizeFileName(string name)
    {
        foreach (var invalid in Path.GetInvalidFileNameChars())
            name = name.Replace(invalid, '_');
        return string.IsNullOrWhiteSpace(name) ? "attachment" : name;
    }

    private void ToggleBaseline(string baseline)
    {
        var block = SelectedBlock();
        block.Baseline = block.Baseline == baseline ? "normal" : baseline;
        PushDocumentToBindings();
        _session.MarkDirty();
        RequestRebuild();
    }

    private void ClearSelectedFormat()
    {
        var block = SelectedBlock();
        block.Bold = block.Italic = block.Underline = block.Strike = false;
        block.Baseline = "normal";
        block.FontFamily = string.Empty;
        block.FontSize = 0;
        block.Foreground = string.Empty;
        block.Background = string.Empty;
        PushDocumentToBindings();
        _session.MarkDirty();
        RequestRebuild();
    }

    private void ScaleSelectedFont(double delta)
    {
        var block = SelectedBlock();
        var current = block.FontSize > 0 ? block.FontSize : 14;
        block.FontSize = Math.Clamp(current + delta, 8, 96);
        PushDocumentToBindings();
        _session.MarkDirty();
        RequestRebuild();
    }

    private void SetSelectedAlignment(string alignment)
    {
        SelectedBlock().Alignment = alignment;
        PushDocumentToBindings();
        _session.MarkDirty();
        RequestRebuild();
    }

    private void ShiftSelectedIndent(int delta)
    {
        var block = SelectedBlock();
        block.IndentLevel = Math.Clamp(block.IndentLevel + delta, -1, 8);
        PushDocumentToBindings();
        _session.MarkDirty();
        RequestRebuild();
    }

    private RichBoardBlock ConvertToImageBlock(RichBoardBlock block)
    {
        block.Kind = "image";
        block.Image ??= new RichImageView();
        return block;
    }

    /// <summary>Checklist item ids are "parentId:itemId"; plain ids address the block itself.</summary>
    private RichBoardBlock? FindChecklistBlock(string tail)
    {
        var page = CurrentPage();
        var direct = page.Blocks.FirstOrDefault(b => b.Id == tail);
        if (direct is not null)
            return direct.Kind == "checklist" ? direct : null;
        var cut = tail.LastIndexOf('_');
        if (cut <= 0)
            return null;
        var viewId = tail[..cut] + ":" + tail[(cut + 1)..];
        return page.Blocks.FirstOrDefault(b => b.Id == viewId && b.Kind == "checklist");
    }

    private static (string? ParentId, string ItemId) SplitItemId(string viewBlockId)
    {
        var colon = viewBlockId.IndexOf(':');
        return colon > 0
            ? (viewBlockId[..colon], viewBlockId[(colon + 1)..])
            : (null, viewBlockId);
    }

    private static string ParentKey(string viewBlockId)
    {
        var (parentId, _) = SplitItemId(viewBlockId);
        return parentId ?? viewBlockId;
    }

    private static bool SplitBlockAndTail(string rest, out string blockId, out string tail)
    {
        // Contract block ids never contain '_'; expr ids ("expr-*") neither.
        var cut = rest.LastIndexOf('_');
        if (cut <= 0)
        {
            blockId = string.Empty;
            tail = string.Empty;
            return false;
        }
        blockId = rest[..cut];
        tail = rest[(cut + 1)..];
        return true;
    }

    private static string ToContractBlockId(RichBoardBlock block)
    {
        var (parentId, _) = SplitItemId(block.Id);
        return parentId ?? block.Id;
    }

    private static void EnsureTableDims(RichBoardBlock block)
    {
        if (block.TableRows <= 0)
            block.TableRows = Math.Max(1, block.TableCells.Keys.Select(RowOf).DefaultIfEmpty(0).Max() + 1);
        if (block.TableCols <= 0)
            block.TableCols = Math.Max(1, block.TableCells.Keys.Select(ColOf).DefaultIfEmpty(0).Max() + 1);
    }

    private static int RowOf(string key)
    {
        var cut = key.IndexOf(',');
        return cut > 0 && int.TryParse(key[..cut], out var row) ? row : 0;
    }

    private static int ColOf(string key)
    {
        var cut = key.IndexOf(',');
        return cut >= 0 && int.TryParse(key[(cut + 1)..], out var col) ? col : 0;
    }

    private static string BindingForControl(string controlName) => controlName switch
    {
        "BoardTitleBox" => "BoardTitle",
        "HeadingBox" => "HeadingText",
        "ParaBox" => "ParaText",
        "Check1Box" => "Check1Text",
        "Check1Done" => "Check1Done",
        "Check2Box" => "Check2Text",
        "Check2Done" => "Check2Done",
        "Cell00" => "Cell00",
        "Cell01" => "Cell01",
        "Cell10" => "Cell10",
        "Cell11" => "Cell11",
        _ => controlName,
    };

    private void PushSelectedInfo()
    {
        var selected = CurrentPage().Blocks.FirstOrDefault(b => b.Id == _selectedBlockId)
            ?? CurrentPage().Blocks.FirstOrDefault();
        if (selected is null)
            return;
        Set("SelectedBlockInfo", $"{selected.Kind}: {(selected.Text.Length > 40 ? selected.Text[..40] : selected.Text)}");
        Set("BoldState", selected.Bold ? "On" : "Off");
        Set("ItalicState", selected.Italic ? "On" : "Off");
        Set("UnderlineState", selected.Underline ? "On" : "Off");
    }

    private void PushDocumentToBindings()
    {
        var doc = _session.Document;
        var page = CurrentPage();
        var heading = page.Blocks.FirstOrDefault(b => b.Kind == "heading");
        var para = page.Blocks.FirstOrDefault(b => b.Kind == "paragraph");
        var checks = page.Blocks.Where(b => b.Kind == "checklist").ToList();
        var table = page.Blocks.FirstOrDefault(b => b.Kind == "table");
        var ink = page.Blocks.FirstOrDefault(b => b.Kind == "ink");
        var selected = page.Blocks.FirstOrDefault(b => b.Id == _selectedBlockId) ?? para ?? heading;

        if (selected is not null)
            _selectedBlockId = selected.Id;

        _syncing = true;
        try
        {
            Set("BoardTitle", doc.Title);
            Set("FilePath", _session.FilePath ?? "memory://boards/default");
            Set("StatusText", _session.Status);
            Set("SectionCount", doc.Sections.Count.ToString());
            Set("PageCount", CurrentSection().Pages.Count.ToString());
            Set("SectionListText", string.Join("  |  ", doc.Sections.Select(s => s.Title)));
            Set("PageListText", string.Join("  |  ", CurrentSection().Pages.Select(p => p.Title)));
            Set("PageTitle", page.Title);
            Set("HeadingText", heading?.Text ?? string.Empty);
            Set("ParaText", para?.Text ?? string.Empty);
            Set("Check1Text", checks.Count > 0 ? checks[0].Text : string.Empty);
            Set("Check1Done", checks.Count > 0 && checks[0].IsChecked);
            Set("Check2Text", checks.Count > 1 ? checks[1].Text : string.Empty);
            Set("Check2Done", checks.Count > 1 && checks[1].IsChecked);
            Set("Cell00", TableCell(table, "0,0"));
            Set("Cell01", TableCell(table, "0,1"));
            Set("Cell10", TableCell(table, "1,0"));
            Set("Cell11", TableCell(table, "1,1"));
            Set("InkSummary", ink is null ? "No ink yet" : $"{ink.InkStrokeCount} stroke(s) — {ink.Text}");
            Set("SelectedBlockInfo", selected is null ? "No block" : $"{selected.Kind}: {(selected.Text.Length > 40 ? selected.Text[..40] : selected.Text)}");
            Set("BoldState", selected?.Bold == true ? "On" : "Off");
            Set("ItalicState", selected?.Italic == true ? "On" : "Off");
            Set("UnderlineState", selected?.Underline == true ? "On" : "Off");
            Set("CanUndo", _session.CanUndo);
            Set("CanRedo", _session.CanRedo);
        }
        finally
        {
            _syncing = false;
        }
    }

    private RichBoardSection CurrentSection() =>
        _session.Document.Sections.FirstOrDefault(s => s.Id == _selectedSectionId)
        ?? _session.Document.Sections.FirstOrDefault()
        ?? throw new InvalidOperationException("Board has no sections.");

    private RichBoardPage CurrentPage()
    {
        var section = CurrentSection();
        return section.Pages.FirstOrDefault(p => p.Id == _selectedPageId)
            ?? section.Pages.FirstOrDefault()
            ?? throw new InvalidOperationException("Section has no pages.");
    }

    private RichBoardBlock SelectedBlock() =>
        CurrentPage().Blocks.FirstOrDefault(b => b.Id == _selectedBlockId)
        ?? CurrentPage().Blocks.FirstOrDefault()
        ?? throw new InvalidOperationException("Page has no blocks.");

    private RichBoardBlock FindOrCreateBlock(string kind)
    {
        var page = CurrentPage();
        var block = page.Blocks.FirstOrDefault(b => b.Kind == kind);
        if (block is null)
        {
            block = new RichBoardBlock { Kind = kind };
            page.Blocks.Add(block);
        }
        return block;
    }

    private RichBoardBlock FindChecklist(int index)
    {
        var page = CurrentPage();
        var checks = page.Blocks.Where(b => b.Kind == "checklist").ToList();
        while (checks.Count <= index)
        {
            var added = new RichBoardBlock { Kind = "checklist", Text = $"Item {checks.Count + 1}" };
            page.Blocks.Add(added);
            checks.Add(added);
        }
        return checks[index];
    }

    private void SetTableCell(string key, string value)
    {
        var table = FindOrCreateBlock("table");
        table.TableCells[key] = value;
    }

    private static string TableCell(RichBoardBlock? table, string key) =>
        table is not null && table.TableCells.TryGetValue(key, out var value) ? value : string.Empty;

    private void ReselectDefaults()
    {
        var firstSection = _session.Document.Sections.FirstOrDefault();
        if (firstSection is null)
            return;
        _selectedSectionId = firstSection.Id;
        _selectedPageId = firstSection.Pages.FirstOrDefault()?.Id ?? _selectedPageId;
        var para = firstSection.Pages.FirstOrDefault()?.Blocks.FirstOrDefault(b => b.Kind == "paragraph");
        if (para is not null)
            _selectedBlockId = para.Id;
    }

    private void ReselectAfterUndo()
    {
        var section = _session.Document.Sections.FirstOrDefault(s => s.Id == _selectedSectionId)
            ?? _session.Document.Sections.FirstOrDefault();
        if (section is null)
            return;
        _selectedSectionId = section.Id;
        var page = section.Pages.FirstOrDefault(p => p.Id == _selectedPageId)
            ?? section.Pages.FirstOrDefault();
        if (page is null)
            return;
        _selectedPageId = page.Id;
        if (page.Blocks.All(b => b.Id != _selectedBlockId))
            _selectedBlockId = page.Blocks.FirstOrDefault()?.Id ?? _selectedBlockId;
    }

    private static IEnumerable<T> FindControls<T>(Control root) where T : Control
    {
        if (root is T match)
            yield return match;
        foreach (var child in LogicalChildren(root))
            foreach (var nested in FindControls<T>(child))
                yield return nested;
    }

    private static IEnumerable<Control> LogicalChildren(Control control)
    {
        if (control is Panel panel)
        {
            foreach (var child in panel.Children)
                if (child is Control c)
                    yield return c;
        }
        else if (control is Decorator decorator && decorator.Child is Control decChild)
        {
            yield return decChild;
        }
        else if (control is ContentControl cc)
        {
            if (cc.Content is Control ccChild)
                yield return ccChild;
        }
        else if (control is ItemsControl ic)
        {
            foreach (var item in ic.Items)
                if (item is Control icChild)
                    yield return icChild;
        }
    }
}
