<Project Sdk="Microsoft.NET.Sdk.Web"><ItemGroup><ProjectReference Include="../Accounts/NineToOne.Accounts.csproj" /><ProjectReference Include="../Accounts/Remote/NineToOne.Accounts.Remote.csproj" /><ProjectReference Include="../Sites/HavenOS.Sites.csproj" /><ProjectReference Include="../Files/CUI/HavenOS.Files.CUI.csproj" /></ItemGroup><PropertyGroup><DefaultItemExcludes>$(DefaultItemExcludes);Tests/**</DefaultItemExcludes></PropertyGroup><ItemGroup><None Update="SubscriptionBuilder.html" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" /></ItemGroup><ItemGroup><EmbeddedResource Include="signin-page.mjs" LogicalName="NineToOne.Web.Remote.signin-page.mjs" /><EmbeddedResource Include="web-oidc-signin.mjs" LogicalName="NineToOne.Web.Remote.web-oidc-signin.mjs" /><EmbeddedResource Include="login-submit.mjs" LogicalName="NineToOne.Web.Remote.login-submit.mjs" /></ItemGroup></Project>
