<Project Sdk="Microsoft.NET.Sdk.Web"><ItemGroup><ProjectReference Include="../Accounts/NineToOne.Accounts.csproj" /><ProjectReference Include="../Sites/HavenOS.Sites.csproj" /><ProjectReference Include="../Files/CUI/HavenOS.Files.CUI.csproj" /></ItemGroup><PropertyGroup><DefaultItemExcludes>$(DefaultItemExcludes);Tests/**</DefaultItemExcludes></PropertyGroup><ItemGroup><None Update="SubscriptionBuilder.html" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" /></ItemGroup></Project>
