<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <AssemblyName>HavenOS.Images</AssemblyName>
    <RootNamespace>HavenOS.Images</RootNamespace>
    <DefaultItemExcludes>$(DefaultItemExcludes);Tests/**;Source\**\*</DefaultItemExcludes>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../shared/src/Haven.Application/Haven.Application.csproj" />
    <ProjectReference Include="../shared/src/Haven.Productivity.NativeUI/Haven.Productivity.NativeUI.csproj" />
    <ProjectReference Include="../../framework/CUI/Runtime/CakeOS.Cui.Runtime.csproj" />
    <PackageReference Include="TagLibSharp" VersionOverride="2.3.0" />
    <EmbeddedResource Include="UI/*.cui" LogicalName="HavenOS.Images.UI.%(Filename)%(Extension)" />
    <AvaloniaResource Remove="**/*.axaml" />
    <AvaloniaXaml Remove="**/*.axaml" />
  </ItemGroup>
</Project>
