<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net10.0</TargetFramework><OutputType>Exe</OutputType><AssemblyName>NineToOne.Accounts.Remote.Specs</AssemblyName><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><EnableDefaultCompileItems>false</EnableDefaultCompileItems></PropertyGroup><ItemGroup><ProjectReference Include="../NineToOne.Accounts.Remote.csproj" /><Compile Include="*.cs" /><Compile Include="../../../Web/RemoteAccountWebFacade.cs" Link="RemoteAccountWebFacade.cs" /></ItemGroup></Project>
