import { DatabaseSync } from "node:sqlite";
import { getMigrations } from "better-auth/db/migration";
import { randomBytes } from "node:crypto";
import { createAuthOptions } from "../src/auth";
import type { Env } from "../src/env";

export async function generateSchema(): Promise<string> {
  const database = new DatabaseSync(":memory:");
  const env = {
    APP_MODE: "local-test-only",
    AUTH_BASE_URL: "http://127.0.0.1:8798",
    API_RESOURCE: "http://127.0.0.1:5095",
    AUTH_SECRET: randomBytes(48).toString("base64url"),
    DB: database,
  } as unknown as Env;

  try {
    const plan = await getMigrations(createAuthOptions(env));
    if (plan.unsafeChanges.length || plan.schemaProblems.length) {
      throw new Error(`Unsafe Better Auth schema plan: ${[...plan.unsafeChanges, ...plan.schemaProblems].join("; ")}`);
    }
    return [
      "-- Generated by scripts/generate-schema.mjs from the pinned Better Auth configuration.",
      "-- Review this migration whenever Better Auth or its OAuth provider version changes.",
      await plan.compileMigrations(),
      "",
    ].join("\n");
  } finally {
    database.close();
  }
}
