<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>HavenOS.Apps.Assistants.MiniComputer</AssemblyName>
    <RootNamespace>HavenOS.Apps.Assistants.MiniComputer</RootNamespace>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Source/**/*.cs" />
    <ProjectReference Include="../HavenOS.Assistants.Core.csproj" />
    <ProjectReference Include="../../MiniComputer/HavenOS.MiniComputer.csproj" />
    <ProjectReference Include="../../shared/src/Haven.Infrastructure/Haven.Infrastructure.csproj" />
  </ItemGroup>
</Project>
